const lyric_trouble_maker = `
<p class="p-msl">1 2 3</p>
<p class="p-msl">니 눈을 보면 난</p>
<p class="p-msl">Trouble Maker</p>
<p class="p-msl">니 곁에 서면 난</p>
<p class="p-msl">Trouble Maker</p>
<p class="p-msl">조금씩 더 더 더</p>
<p class="p-msl">갈수록 더 더 더</p>
<p class="p-msl">이젠 내 맘을</p>
<p class="p-msl">나도 어쩔 수 없어</p>
<p class="p-msl highlighted">니가 나를 잊지 못하게</p>
<p class="p-msl highlighted">자꾸 니 앞에서 또</p>
<p class="p-msl highlighted">니 맘 자꾸 내가 흔들어</p>
<p class="p-msl highlighted">벗어날 수 없도록</p>
<p class="p-msl">니 입술을 또 훔치고</p>
<p class="p-msl">멀리 달아나버려</p>
<p class="p-msl">난 Trou a a a ble Trouble</p>
<p class="p-msl">Trou Trouble Maker</p>
<p class="p-msl">Trouble Maker Trouble Maker</p>
<p class="p-msl">Trouble Maker Trouble Maker</p>
<p class="p-msl highlighted">니 맘을 깨물고 도망칠 거야</p>
<p class="p-msl highlighted">고양이처럼 넌 자꾸 안달이 날 거야</p>
<p class="p-msl highlighted">내 앞으로 와 어서 화내보렴</p>
<p class="p-msl highlighted">내 섹시한 걸음 니 머리 속에</p>
<p class="p-msl highlighted">발동을 거는 은근한 스킨십</p>
<p class="p-msl highlighted">얼굴에 비친 못 참아 죽겠단 니 눈빛</p>
<p class="p-msl">갈수록 깊이 더 빠져들어 알수록</p>
<p class="p-msl">니가 더 맘에 들어 Baby</p>
<p class="p-msl">아무래도 니 생각에 취했나봐</p>
<p class="p-msl">Lady I never never never stop</p>
<p class="p-msl highlighted">니가 나를 잊지 못하게</p>
<p class="p-msl highlighted">자꾸 니 앞에서 또</p>
<p class="p-msl highlighted">니 맘 자꾸 내가 흔들어</p>
<p class="p-msl highlighted">벗어날 수 없도록</p>
<p class="p-msl">니 입술을 또 훔치고</p>
<p class="p-msl">멀리 달아나버려</p>
<p class="p-msl">난 Trou a a a ble Trouble</p>
<p class="p-msl">Trou Trouble Maker</p>
<p class="p-msl">Trouble Maker Trouble Maker</p>
<p class="p-msl">Trouble Maker Trouble Maker</p>
<p class="p-msl">어떻게 널 내 맘에</p>
<p class="p-msl">담아둘 수 있는지 Trouble Maker</p>
<p class="p-msl">그냥 내 맘이 가는대로</p>
<p class="p-msl">이젠 I never never stop</p>
<p class="p-msl">멈출 수 없어</p>
<p class="p-msl highlighted">니가 나를 잊지 못하게</p>
<p class="p-msl highlighted">자꾸 니 앞에서 또</p>
<p class="p-msl highlighted">니 맘 자꾸 내가 흔들어</p>
<p class="p-msl highlighted">벗어날 수 없도록</p>
<p class="p-msl">니 입술을 또 훔치고</p>
<p class="p-msl">멀리 달아나버려</p>
<p class="p-msl">난 Trou a a a ble Trouble</p>
<p class="p-msl">Trou Trouble Maker</p>
<p class="p-msl">Trouble Maker Trouble Maker</p>
<p class="p-msl">Trouble Maker Trouble Maker</p>
`;

const lyric_illusion = `
<p class="p-msl">You’re so yummy yummy yummy</p>
<p class="p-msl">In my tummy tummy tummy</p>
<p class="p-msl"></p>
<p class="p-msl">Look at you 빨라지는 걸음걸이</p>
<p class="p-msl">Look at me 호기심을 자극하지</p>
<p class="p-msl">Look at them 알아챌 수 없는 거리</p>
<p class="p-msl">Baby don’t panic 한밤의 Party</p>
<p class="p-msl"></p>
<p class="p-msl">차올라 달이 딱 좋은 Timing</p>
<p class="p-msl">이건 비밀이야 쉿 우리만의</p>
<p class="p-msl highlighted">한밤의 Party 널 끌어당김</p>
<p class="p-msl highlighted">어쩌니 내게 뺏겨버린 환심</p>
<p class="p-msl"></p>
<p class="p-msl">몽롱한 기분이 좋은 Tonight</p>
<p class="p-msl">색다른 세계로 이끄는 Light</p>
<p class="p-msl"></p>
<p class="p-msl">Follow me, Come and get illusion</p>
<p class="p-msl">한입에 삼켜 널 Delicious</p>
<p class="p-msl">아찔한 미끼로 Hook up</p>
<p class="p-msl">관심을 먹고 Growing up</p>
<p class="p-msl">Follow me, Come and get illusion</p>
<p class="p-msl">몸집을 불려가 Delicious</p>
<p class="p-msl">점점 더 커지는 Fire</p>
<p class="p-msl">관심을 먹고 Growing up</p>
<p class="p-msl"></p>
<p class="p-msl highlighted">(Will o' the wisp)</p>
<p class="p-msl highlighted">겁내지 말고 이리 온</p>
<p class="p-msl highlighted">(Will o' the wisp)</p>
<p class="p-msl highlighted">겁내지 말고 이리 온</p>
<p class="p-msl"></p>
<p class="p-msl">Easy peasy 너도 알다시피</p>
<p class="p-msl">When you dizzy 내겐 그저 Dish</p>
<p class="p-msl">도깨비불 너를 놀려 Boo</p>
<p class="p-msl">예상 못 한 순간 등장하지 불쑥</p>
<p class="p-msl"></p>
<p class="p-msl">첨 보는 Style 멋모를 Timing</p>
<p class="p-msl">너의 약점에다 Hit! It’s so funny</p>
<p class="p-msl">한밤의 Party 널 끌어당김</p>
<p class="p-msl">알아도 막을 수 없는 반칙</p>
<p class="p-msl"></p>
<p class="p-msl">낯선 이 기분이 묘한 Tonight</p>
<p class="p-msl highlighted">감춰둔 본능을 이끄는 Light</p>
<p class="p-msl"></p>
<p class="p-msl">Follow me, Come and get illusion</p>
<p class="p-msl">한입에 삼켜 널 Delicious</p>
<p class="p-msl">아찔한 미끼로 Hook up</p>
<p class="p-msl">관심을 먹고 Growing up</p>
<p class="p-msl">Follow me, Come and get illusion</p>
<p class="p-msl">몸집을 불려가 Delicious</p>
<p class="p-msl">점점 더 커지는 Fire</p>
<p class="p-msl">관심을 먹고 Growing up</p>
<p class="p-msl highlighted">(Will o' the wisp)</p>
<p class="p-msl highlighted">겁내지 말고 이리 온</p>
<p class="p-msl highlighted">(Will o' the wisp)</p>
<p class="p-msl highlighted">겁내지 말고 이리 온</p>
<p class="p-msl"></p>
<p class="p-msl">Yummy yummy yummy</p>
<p class="p-msl">In your tummy tummy tummy</p>
<p class="p-msl">놀란 너의 Face 나를 저격하는 Taste</p>
<p class="p-msl">멀리멀리 달아나도 소용없어 이미</p>
<p class="p-msl">Come get illusion</p>
<p class="p-msl">So fool</p>
<p class="p-msl"></p>
<p class="p-msl">Follow me, Come and get illusion</p>
<p class="p-msl">유일한 목격자 You’re the one</p>
<p class="p-msl">방심한 틈을 타 Swallow</p>
<p class="p-msl">환상을 먹고 Growing up</p>
<p class="p-msl">Follow me, Come and get illusion</p>
<p class="p-msl">순진한 먹잇감 Delicious</p>
<p class="p-msl">단번에 노리는 Hunter</p>
<p class="p-msl">네 맘을 뺏어 Growing up</p>
<p class="p-msl"></p>
<p class="p-msl highlighted">(Will o' the wisp)</p>
<p class="p-msl highlighted">겁내지 말고 이리 온</p>
<p class="p-msl highlighted">(Will o' the wisp)</p>
<p class="p-msl highlighted">겁내지 말고 이리 온</p>
`;

const lyric_lipstic = `
<p class="p-msl">립스틱 스틱 세우고</p>
<p class="p-msl">립스틱 스틱 세우고</p>
<p class="p-msl">어찌나 눈이 높던지</p>
<p class="p-msl">애인이 있는 건지</p>
<p class="p-msl">살짝 시크해보여</p>
<p class="p-msl">하나도 관심 없는 척</p>
<p class="p-msl">속이는 거 다 알아</p>
<p class="p-msl">흘리고 다니잖아</p>
<p class="p-msl">오똑한 콧날에 베일 것 같아</p>
<p class="p-msl">짜릿 짜릿 네 눈빛에 녹을 것 같아</p>
<p class="p-msl">구릿빛 피부가 달콤해 보여</p>
<p class="p-msl highlighted">아슬아슬 다가가서 훔치고 싶어</p>
<p class="p-msl highlighted">립스틱 스틱 세우고</p>
<p class="p-msl highlighted">내 입술에 바르고</p>
<p class="p-msl highlighted">잘 다려진 하얀 셔츠 위에</p>
<p class="p-msl highlighted">살짝 묻히고</p>
<p class="p-msl" highlighted>립스틱 스틱 세우고</p>
<p class="p-msl" highlighted>네 입술에 맞추고</p>
<p class="p-msl highlighted">아찔아찔 솟은 쇄골 위에</p>
<p class="p-msl highlighted">몰래 묻히고 어머어머</p>
<p class="p-msl highlighted">어어어어 어머어머</p>
<p class="p-msl">몰래 묻히고 어머어머</p>
<p class="p-msl">어어어어 어머어머</p>
<p class="p-msl">어쩌다 그리 된 건지</p>
<p class="p-msl">사연이 있는 건지</p>
<p class="p-msl">살짝 화가나 보여</p>
<p class="p-msl">사실 좀 미안하지만</p>
<p class="p-msl">즐기는 거 다 알아</p>
<p class="p-msl">몰래 웃고 있잖아</p>
<p class="p-msl">촉촉한 눈빛에 빠질 것 같아</p>
<p class="p-msl">찌릿 찌릿 네 향기에 취할 것 같아</p>
<p class="p-msl">우윳빛 피부가 눈부셔 보여</p>
<p class="p-msl">아슬아슬 다가가서 훔치고 싶어</p>
<p class="p-msl highlighted">립스틱 스틱 세우고</p>
<p class="p-msl highlighted">내 입술에 바르고</p>
<p class="p-msl highlighted">잘 다려진 하얀 셔츠 위에</p>
<p class="p-msl highlighted">살짝 묻히고</p>
<p class="p-msl highlighted">립스틱 스틱 세우고</p>
<p class="p-msl highlighted">네 입술에 맞추고</p>
<p class="p-msl highlighted">아찔아찔 솟은 쇄골 위에</p>
<p class="p-msl highlighted">몰래 묻히고 어머어머</p>
<p class="p-msl highlighted">어어어어 어머어머</p>
<p class="p-msl highlighted">몰래 묻히고 어머어머</p>
<p class="p-msl highlighted">어어어어 어머어머</p>
<p class="p-msl">좀 빼지마 가만히 둘 순 없어</p>
<p class="p-msl">널 널 널</p>
<p class="p-msl">이러지마 오늘 처음 봤잖아</p>
<p class="p-msl">립스틱 스틱 세우고</p>
<p class="p-msl">내 입술에 바르고</p>
<p class="p-msl">잘 다려진 하얀 셔츠 위에</p>
<p class="p-msl">살짝 묻히고</p>
<p class="p-msl">립스틱 스틱 세우고</p>
<p class="p-msl">네 입술에 맞추고</p>
<p class="p-msl">아찔아찔 솟은 쇄골 위에</p>
<p class="p-msl">몰래 묻히고 어머어머</p>
<p class="p-msl">어어어어 어머어머</p>
<p class="p-msl">몰래 묻히고 어머어머</p>
<p class="p-msl">어어어어 어머어머</p>

`;

const lyric_i_feel_you = `
<p class="p-msl">내게 걸어놓은 마법이 뭔지</p>
<p class="p-msl">헤어 나오질 못하고 있어</p>
<p class="p-msl">한번도 이런 적이 없이</p>
<p class="p-msl">흔들린 적이 없었던 난데 No</p>
<p class="p-msl highlighted">Woo 하루 종일 이래 네 생각에 취해</p>
<p class="p-msl highlighted">Woo 기다리기만 해 널 만나러 가게</p>
<p class="p-msl">Woo woo baby 어쩌면 좋아</p>
<p class="p-msl highlighted">너 없인 못 살 것만 같아</p>
<p class="p-msl">Woo baby</p>
<p class="p-msl">I Feel You</p>
<p class="p-msl">혼자 있어도 너의 손길이 느껴져</p>
<p class="p-msl">하루 종일 나를 만져</p>
<p class="p-msl">I Feel You</p>
<p class="p-msl highlighted">빠져있는데 헤어나올 수가 없어</p>
<p class="p-msl highlighted">너에게 달려갈 생각뿐이 없어</p>
<p class="p-msl highlighted">점점 더 빠져만 가</p>
<p class="p-msl highlighted">점점 더 미쳐만 가</p>
<p class="p-msl">점점 더 어떻게 나 Baby</p>
<p class="p-msl">네 손길이 아직도 나를스치고 있는 것만 같아</p>
<p class="p-msl">네 목소리가 내 귓가에</p>
<p class="p-msl">계속 속삭이는 것만 같아 No</p>
<p class="p-msl highlighted">Woo 하루 종일 이래 네 생각에 취해</p>
<p class="p-msl highlighted">Woo 기다리기만 해 널 만나러 가게</p>
<p class="p-msl">Woo woo baby 어쩌면 좋아</p>
<p class="p-msl highlighted">너 없인 못 살 것만 같아</p>
<p class="p-msl">Woo babyI Feel You</p>
<p class="p-msl">혼자 있어도 너의 손길이 느껴져</p>
<p class="p-msl">하루 종일 나를 만져</p>
<p class="p-msl">I Feel You</p>
<p class="p-msl highlighted">빠져있는데 헤어나올 수가 없어</p>
<p class="p-msl highlighted">너에게 달려갈 생각뿐이 없어</p>
<p class="p-msl">눈 감아도 들려달콤한 숨결 느껴</p>
<p class="p-msl">그만 날 보고 불 꺼니 시선이 더 날 붉혀</p>
<p class="p-msl">손발 끝 간질거려와</p>
<p class="p-msl">달아오르는 체온 숨 가빠와</p>
<p class="p-msl">더 이상은 참을 수가 없어 나</p>
<p class="p-msl">이제 Please baby be mine</p>
<p class="p-msl">I Feel You</p>
<p class="p-msl">혼자 있어도 너의 손길이 느껴져</p>
<p class="p-msl">하루 종일 나를 만져</p>
<p class="p-msl">I Feel You</p>
<p class="p-msl highlighted">빠져있는데 헤어나올 수가 없어</p>
<p class="p-msl highlighted">너에게 달려갈 생각뿐이 없어</p>
<p class="p-msl">점점 더 빠져만 가</p>
<p class="p-msl">점점 더 미쳐만 가</p>
<p class="p-msl">점점 더 어떻게 나</p>
<p class="p-msl">Baby</p>

`;

const lyric_heart_attack = `
<p class="p-msl">A ye Brave sound</p>
<p class="p-msl">And it goes a little something like this</p>
<p class="p-msl">완전 반해 반해 버렸어요</p>
<p class="p-msl">부드러운 목소리에</p>
<p class="p-msl highlighted">반해 반해 버렸어요</p>
<p class="p-msl highlighted">난 떨려</p>
<p class="p-msl">AOA Let's Go</p>
<p class="p-msl highlighted">내가 미쳤나 봐 왜 또 이러지</p>
<p class="p-msl highlighted">내 마음 열여덟 소녀 마냥</p>
<p class="p-msl highlighted">막 쿵쿵대</p>
<p class="p-msl highlighted">숨길 수 없나 봐 난 매일 이러지</p>
<p class="p-msl highlighted">눈이라도 마주치면</p>
<p class="p-msl highlighted">귀까지 확 빨개져</p>
<p class="p-msl">이해 못해</p>
<p class="p-msl">네가 걔를 못 봐서 그래</p>
<p class="p-msl">딱 첫눈에 확 반해 버린다는 말에</p>
<p class="p-msl">그 마음 이해 가더라</p>
<p class="p-msl">나도 좀 알겠더라</p>
<p class="p-msl highlighted">널 처음 본 그 순간</p>
<p class="p-msl highlighted">완전 반해 반해 버렸어요</p>
<p class="p-msl">넓은 어깨 날렵한 눈매에</p>
<p class="p-msl">부드러운 목소리에</p>
<p class="p-msl">반해 반해 버렸어요</p>
<p class="p-msl highlighted">너의 얇고 긴 손가락만 봐도</p>
<p class="p-msl highlighted">난 떨려</p>
<p class="p-msl highlighted">어머나 자꾸만 심쿵해</p>
<p class="p-msl highlighted">널 보면 볼수록</p>
<p class="p-msl highlighted">가슴이 쿵쿵대 나도 모르겠어</p>
<p class="p-msl highlighted">심쿵해 나 어쩌면 좋아</p>
<p class="p-msl">자꾸만 네 품에</p>
<p class="p-msl">꼭 안기고 싶어 baby</p>
<p class="p-msl highlighted">어쩌다 눈이라도 마주치면</p>
<p class="p-msl highlighted">난 심쿵 거려</p>
<p class="p-msl highlighted">너의 작은 관심이라도 받을까</p>
<p class="p-msl highlighted">아등바등 거려</p>
<p class="p-msl">너는 대체 걔가 뭐가 그리 좋아</p>
<p class="p-msl">라고 묻는 친구들에게 말해</p>
<p class="p-msl">야 모르면 말을 말어</p>
<p class="p-msl">이해 못해 네가 걔를 못 봐서 그래</p>
<p class="p-msl">딱 첫눈에 확 반해 버린다는 말에</p>
<p class="p-msl">그 마음 이해 가더라</p>
<p class="p-msl">나도 좀 알겠더라</p>
<p class="p-msl highlighted">널 처음 본 그 순간</p>
<p class="p-msl highlighted">완전 반해 반해 버렸어요</p>
<p class="p-msl">넓은 어깨 날렵한 눈매에</p>
<p class="p-msl">부드러운 목소리에</p>
<p class="p-msl">반해 반해 버렸어요</p>
<p class="p-msl highlighted">너의 얇고 긴 손가락만 봐도</p>
<p class="p-msl highlighted">난 떨려</p>
<p class="p-msl highlighted">어머나 자꾸만 심쿵해</p>
<p class="p-msl highlighted">널 보면 볼수록</p>
<p class="p-msl highlighted">가슴이 쿵쿵대 나도 모르겠어</p>
<p class="p-msl highlighted">심쿵해 나 어쩌면 좋아</p>
<p class="p-msl">자꾸만 네 품에</p>
<p class="p-msl">꼭 안기고 싶어 baby</p>
<p class="p-msl">오 나의 왕자님 어디를 보나요</p>
<p class="p-msl">바로 여기 내가 있는데요</p>
<p class="p-msl">너무나 멋진 그대</p>
<p class="p-msl">난 그대 하나면 돼</p>
<p class="p-msl">난 그대 없이 못 살아요</p>
<p class="p-msl">완전 반해 반해 버렸어요</p>
<p class="p-msl">부드러운 목소리에</p>
<p class="p-msl highlighted">반해 반해 버렸어요</p>
<p class="p-msl highlighted">난 떨려</p>
<p class="p-msl highlighted">어머나 자꾸만 심쿵해</p>
<p class="p-msl">Everybody say What AOA</p>
<p class="p-msl">쿵쿵대</p>
<p class="p-msl">And it goes a little something like this</p>
<p class="p-msl">심쿵해</p>
<p class="p-msl">한번 더 say What AOA</p>
<p class="p-msl">네 품에 꼭 안기고 싶어 baby</p>
`;

const lyric_gee = `
<p class="p-msl">Uh Huh Listen Boy </p>
<p class="p-msl">My First Love Story </p>
<p class="p-msl">My Angel and My Girl</p>
<p class="p-msl">My Sunshine</p>
<p class="p-msl">Uh Uh Let's go</p>
<p class="p-msl">너무 너무 멋져 눈이 눈이 부셔</p>
<p class="p-msl highlighted">숨을 못 쉬겠어 떨리는 Girl</p>
<p class="p-msl">Gee Gee Gee Gee Baby Baby Baby</p>
<p class="p-msl">Gee Gee Gee Gee Baby Baby Baby</p>
<p class="p-msl highlighted">너무 부끄러워 쳐다 볼 수 없어</p>
<p class="p-msl highlighted">사랑에 빠져서 수줍은 Girl</p>
<p class="p-msl">Gee Gee Gee Gee Baby Baby Baby</p>
<p class="p-msl">Gee Gee Gee Gee</p>
<p class="p-msl">Be Be Be Be Be Be</p>
<p class="p-msl">어떻게 하죠</p>
<p class="p-msl">어떡 어떡하죠</p>
<p class="p-msl">떨리는 나는</p>
<p class="p-msl" highlighted>떨리는 나는요</p>
<p class="p-msl highlighted">두근 두근 두근 두근두근 두근거려</p>
<p class="p-msl highlighted">밤엔 잠도 못 이루죠</p>
<p class="p-msl">나는 나는 바본가봐요</p>
<p class="p-msl highlighted">그대 그대밖에 모르는 바보</p>
<p class="p-msl">그래요 그댈 보는 난</p>
<p class="p-msl">너무 반짝 반짝 눈이 부셔</p>
<p class="p-msl">No No No No No</p>
<p class="p-msl">너무 깜짝 깜짝 놀란 나는</p>
<p class="p-msl">Oh Oh Oh Oh Oh</p>
<p class="p-msl">너무 짜릿 짜릿 몸이 떨려</p>
<p class="p-msl">Gee Gee Gee Gee Gee</p>
<p class="p-msl">Oh 젖은 눈빛 Oh Yeah</p>
<p class="p-msl">좋은 향기 Oh Yeah Yeah Yeah</p>
<p class="p-msl">너무 너무 예뻐 맘이 너무 예뻐</p>
<p class="p-msl">첫 눈에 반했어 꼭 짚은 Girl</p>
<p class="p-msl">Gee Gee Gee Gee Baby Baby Baby</p>
<p class="p-msl">Gee Gee Gee Gee Baby Baby Baby</p>
<p class="p-msl highlighted">너무나 뜨거워 만질 수가 없어</p>
<p class="p-msl highlighted">사랑에 타버려 후끈한 Girl</p>
<p class="p-msl">Gee Gee Gee Gee Baby Baby Baby</p>
<p class="p-msl">Gee Gee Gee GeeBe Be Be Be Be Be</p>
<p class="p-msl">어쩌면 좋아</p>
<p class="p-msl">어쩌면 좋아요</p>
<p class="p-msl">수줍은 나는</p>
<p class="p-msl highlighted">수줍은 나는요</p>
<p class="p-msl highlighted">몰라 몰라 몰라 몰라몰라 몰라 하며</p>
<p class="p-msl highlighted">매일 그대만 그리죠</p>
<p class="p-msl">친한 친구들은 말하죠</p>
<p class="p-msl">정말 너는 정말 못 말려</p>
<p class="p-msl">바보 하지만 그댈 보는 난</p>
<p class="p-msl">너무 반짝 반짝 눈이 부셔</p>
<p class="p-msl">No No No No No</p>
<p class="p-msl">너무 깜짝 깜짝 놀란 나는</p>
<p class="p-msl">Oh Oh Oh Oh Oh</p>
<p class="p-msl">너무 짜릿 짜릿 몸이 떨려</p>
<p class="p-msl">Gee Gee Gee Gee Gee</p>
<p class="p-msl">Oh 젖은 눈빛 Oh Yeah</p>
<p class="p-msl">좋은 향기 Oh Yeah Yeah Yeah</p>
<p class="p-msl">말도 못했는 걸</p>
<p class="p-msl">너무 부끄러워 하는 난</p>
<p class="p-msl">용기가 없는 걸까</p>
<p class="p-msl">어떡해야 좋은걸까</p>
<p class="p-msl highlighted">두근 두근 맘 졸이며</p>
<p class="p-msl highlighted">바라보고 있는 난</p>
<p class="p-msl">너무 반짝 반짝 눈이 부셔</p>
<p class="p-msl">No No No No No</p>
<p class="p-msl">너무 깜짝 깜짝 놀란 나는</p>
<p class="p-msl">Oh Oh Oh Oh Oh</p>
<p class="p-msl">너무 짜릿 짜릿 몸이 떨려</p>
<p class="p-msl">Gee Gee Gee Gee Gee</p>
<p class="p-msl">Oh 젖은 눈빛 Oh Yeah</p>
<p class="p-msl">좋은 향기 Oh Yeah</p>
<p class="p-msl">너무 반짝 반짝 눈이 부셔</p>
<p class="p-msl">No No No No No</p>
<p class="p-msl">너무 깜짝 깜짝 놀란 나는</p>
<p class="p-msl">Oh Oh Oh Oh Oh</p>
<p class="p-msl">너무 짜릿 짜릿 몸이 떨려</p>
<p class="p-msl">Gee Gee Gee Gee Gee</p>
<p class="p-msl">Oh 젖은 눈빛 Oh Yeah</p>
<p class="p-msl">좋은 향기 Oh Yeah Yeah Yeah</p>
`;
const lyric_boodoo_doll = `
<p class="p-msl">나를 불러 네가 맘이 아플 때</p>
<p class="p-msl">내게만 털어놔 누굴 원하는데</p>
<p class="p-msl">시간을 돌려줄까</p>
<p class="p-msl">마음을 갖다 줄까</p>
<p class="p-msl">잊을 수 없을 땐 가져야 하잖아</p>
<p class="p-msl">나를 믿고 따라 해봐</p>
<p class="p-msl">그는 내게 돌아온다</p>
<p class="p-msl">시간은 너의 편</p>
<p class="p-msl">넌 그냥 기다려라</p>
<p class="p-msl">그가 널 울린 만큼</p>
<p class="p-msl">내가 다 울려줄게</p>
<p class="p-msl ">째깍 째깍 다 이뤄지리라</p>
<p class="p-msl">가질 수 없다면</p>
<p class="p-msl highlighted">그냥 널 위해 살겠어</p>
<p class="p-msl highlighted">얼마든지 너라면</p>
<p class="p-msl highlighted">다칠 준비가 돼 있어</p>
<p class="p-msl">이제부터 잘 봐 내가 뭘 하는지</p>
<p class="p-msl highlighted">너라면 한 몸 아깝지 않은 나</p>
<p class="p-msl">이름만 대 누구든</p>
<p class="p-msl">내가 다 데려올 거야</p>
<p class="p-msl">째깍 째깍 다 이뤄지리라</p>
<p class="p-msl highlighted">안길 수 없다면 날 밟고 일어서</p>
<p class="p-msl">누구도 함부로 널 못 대하게</p>
<p class="p-msl">어떠한 이유라 해도</p>
<p class="p-msl">넌 내가 필요하다</p>
<p class="p-msl">널 위해 싸우는</p>
<p class="p-msl">인형이 돼 줄 나</p>
<p class="p-msl">아픈 눈을 질끈 감고</p>
<p class="p-msl">너를 위해 달려간다</p>
<p class="p-msl">제발 나를 떠나지만 마라</p>
<p class="p-msl" highlighted>네가 원하는 건 다 가져다줄게</p>
<p class="p-msl">째깍 째깍 다 이뤄지리라</p>
<p class="p-msl">망가진다 해도</p>
<p class="p-msl">너의 손끝에서라면</p>
<p class="p-msl">온 세상의 눈물을</p>
<p class="p-msl">다 흘릴 내가 여기 있어</p>
<p class="p-msl">이제부터 잘 봐 내가 뭘 하는지</p>
<p class="p-msl highlighted">너라면 한 몸 아깝지 않은 나</p>
<p class="p-msl">이름만 대 누구든</p>
<p class="p-msl">내가 다 데려올 거야</p>
<p class="p-msl">째깍 째깍 다 이뤄지리라</p>
<p class="p-msl">Should I go Should I stay</p>
<p class="p-msl">Nobody knows Whoo</p>
<p class="p-msl">Should I go Should I stay</p>
<p class="p-msl">Nobody knows Whoo</p>
<p class="p-msl">Yeah 지옥의 문을 열어라</p>
<p class="p-msl">그녀를 눈물 흘리게 만든</p>
<p class="p-msl">죄인아 피눈물 흘려라</p>
<p class="p-msl">불러라 저주의 노래 네</p>
<p class="p-msl">내면에 감춘 분노들을 말해 봐</p>
<p class="p-msl highlighted">내 육신은 널 위한 제물이돼</p>
<p class="p-msl highlighted">네 행복에 나를 바칠게</p>
<p class="p-msl">웃는 너의 얼굴 한 번이면 족해</p>
<p class="p-msl">내가 대신 다 해 네가 바라는 것</p>
<p class="p-msl">내 남은 시간들이 줄어든대도</p>
<p class="p-msl">누가 됐든 잘 봐 그녈 울리지 마</p>
<p class="p-msl">더 이상 잃을 무엇도 없는 나</p>
<p class="p-msl">그 누구도 모르는</p>
<p class="p-msl">내 가슴속의 슬픔은</p>
<p class="p-msl">째깍 째깍 다 사라지리라</p>
<p class="p-msl">Should I go Should I stay</p>
<p class="p-msl">Nobody knows Whoo</p>
<p class="p-msl">Should I go Should I stay</p>
<p class="p-msl">Nobody knows Whoo</p>
<p class="p-msl">다 이뤄지리라</p>
`;

const lyric_fake_love = `
<p class="p-msl highlighted">널 위해서라면 난</p>
<p class="p-msl highlighted">슬퍼도 기쁜 척 할 수가 있었어</p>
<p class="p-msl highlighted">널 위해서라면 난</p>
<p class="p-msl highlighted">아파도 강한 척 할 수가 있었어</p>
<p class="p-msl">사랑이 사랑만으로 완벽하길</p>
<p class="p-msl">내 모든 약점들은 다 숨겨지길</p>
<p class="p-msl">이뤄지지 않는 꿈속에서</p>
<p class="p-msl">피울 수 없는 꽃을 키웠어</p>
<p class="p-msl">I'm so sick of this</p>
<p class="p-msl">Fake Love Fake Love Fake Love</p>
<p class="p-msl">I'm so sorry but it's</p>
<p class="p-msl">Fake Love Fake Love Fake Love</p>
<p class="p-msl">I wanna be a good man just for you</p>
<p class="p-msl">세상을 줬네 just for you</p>
<p class="p-msl">전부 바꿨어 just for you</p>
<p class="p-msl">Now I dunno me who are you</p>
<p class="p-msl">우리만의 숲 너는 없었어</p>
<p class="p-msl">내가 왔던 route 잊어버렸어</p>
<p class="p-msl">나도 내가 누구였는지도</p>
<p class="p-msl">잘 모르게 됐어</p>
<p class="p-msl">거울에다 지껄여봐 너는 대체 누구니</p>
<p class="p-msl highlighted">널 위해서라면 난</p>
<p class="p-msl highlighted">슬퍼도 기쁜 척 할 수가 있었어</p>
<p class="p-msl highlighted">널 위해서라면 난</p>
<p class="p-msl highlighted">아파도 강한 척 할 수가 있었어</p>
<p class="p-msl">사랑이 사랑만으로 완벽하길</p>
<p class="p-msl">내 모든 약점들은 다 숨겨지길</p>
<p class="p-msl">이뤄지지 않는 꿈속에서</p>
<p class="p-msl">피울 수 없는 꽃을 키웠어</p>
<p class="p-msl">Love you so bad Love you so bad</p>
<p class="p-msl highlighted">널 위해 예쁜 거짓을 빚어내</p>
<p class="p-msl">Love it’s so mad</p>
<p class="p-msl">Love it’s so mad</p>
<p class="p-msl highlighted">날 지워 너의 인형이 되려 해</p>
<p class="p-msl">Love you so bad</p>
<p class="p-msl">Love you so bad</p>
<p class="p-msl highlighted">널 위해 예쁜 거짓을 빚어내</p>
<p class="p-msl">Love it’s so mad</p>
<p class="p-msl">Love it’s so mad</p>
<p class="p-msl highlighted">날 지워 너의 인형이 되려 해</p>
<p class="p-msl">I'm so sick of this</p>
<p class="p-msl">Fake Love Fake Love Fake Love</p>
<p class="p-msl">I'm so sorry but it's</p>
<p class="p-msl">Fake Love Fake Love Fake Love</p>
<p class="p-msl">Why you sad I don't know 난 몰라</p>
<p class="p-msl">웃어봐 사랑해 말해봐</p>
<p class="p-msl">나를 봐 나조차도 버린 나</p>
<p class="p-msl">너조차 이해할 수 없는 나</p>
<p class="p-msl">낯설다 하네</p>
<p class="p-msl highlighted">니가 좋아하던 나로 변한 내가</p>
<p class="p-msl">아니라 하네</p>
<p class="p-msl">예전에 니가 잘 알고 있던 내가</p>
<p class="p-msl highlighted">아니긴 뭐가 아냐 난 눈 멀었어</p>
<p class="p-msl">사랑은 뭐가 사랑</p>
<p class="p-msl">It's all fake love</p>
<p class="p-msl">Woo I dunno I dunno I dunno why</p>
<p class="p-msl">Woo 나도 날 나도 날 모르겠어</p>
<p class="p-msl">Woo I just know I just know</p>
<p class="p-msl">I just know why</p>
<p class="p-msl">Cuz it’s all Fake Love</p>
<p class="p-msl">Fake Love Fake Love</p>
<p class="p-msl">Love you so bad Love you so bad</p>
<p class="p-msl highlighted">널 위해 예쁜 거짓을 빚어내</p>
<p class="p-msl">Love it’s so mad</p>
<p class="p-msl">Love it’s so mad</p>
<p class="p-msl highlighted">날 지워 너의 인형이 되려 해</p>
<p class="p-msl">Love you so bad Love you so bad</p>
<p class="p-msl highlighted">널 위해 예쁜 거짓을 빚어내</p>
<p class="p-msl">Love it’s so mad</p>
<p class="p-msl">Love it’s so mad</p>
<p class="p-msl highlighted">날 지워 너의 인형이 되려 해</p>
<p class="p-msl">I'm so sick of this</p>
<p class="p-msl">Fake Love Fake Love Fake Love</p>
<p class="p-msl">I'm so sorry but it's</p>
<p class="p-msl">Fake Love Fake Love Fake Love</p>
<p class="p-msl highlighted">널 위해서라면 난</p>
<p class="p-msl highlighted">슬퍼도 기쁜 척 할 수가 있었어</p>
<p class="p-msl highlighted">널 위해서라면 난</p>
<p class="p-msl highlighted">아파도 강한 척 할 수가 있었어</p>
<p class="p-msl">사랑이 사랑만으로 완벽하길</p>
<p class="p-msl">내 모든 약점들은 다 숨겨지길</p>
<p class="p-msl">이뤄지지 않는 꿈속에서</p>
<p class="p-msl">피울 수 없는 꽃을 키웠어</p>
`;

const lyric_beautiful = `<p class="p-msl">왜 너야 미쳐버릴 것 같아</p>
<p class="p-msl">대체 뭐야 반해버린 것 같아</p>
<p class="p-msl">하루 종일 머릿속에 맴맴 돌아버려</p>
<p class="p-msl">물음표가 매일매일</p>
<p class="p-msl">가시 돋친 걸 알면서도 갖고 싶어</p>
<p class="p-msl">red rose</p>
<p class="p-msl">가시 줄기엔 아름다운</p>
<p class="p-msl">장미가 피는 법</p>
<p class="p-msl">진한 빨강 꽃말은 널 사랑한단 것</p>
<p class="p-msl">온 몸에 피가 나도 널 안고 싶어</p>
<p class="p-msl">Cuz I think about you errday</p>
<p class="p-msl">이미 중독인 걸 말해 뭐해</p>
<p class="p-msl">니가 날 만지면 온몸이 반응해</p>
<p class="p-msl">니가 있어야 살 수 있어</p>
<p class="p-msl">Every day every night</p>
<p class="p-msl">I can feel you</p>
<p class="p-msl">넌 너무 아름다워</p>
<p class="p-msl">눈을 뗄 수가 없어</p>
<p class="p-msl highlighted">꽃에 핀 가시같이 찔릴 것 같아도</p>
<p class="p-msl highlighted">널 갖고 싶어</p>
<p class="p-msl">So beautiful so beautiful</p>
<p class="p-msl">넌 너무 예뻐 슬프도록 아름다워</p>
<p class="p-msl">Too beautiful to handle</p>
<p class="p-msl">Two fingers thumbs up</p>
<p class="p-msl">감탄사를 던져 맨 정신을 벗겨</p>
<p class="p-msl">미쳐 돌아버릴 것 같아</p>
<p class="p-msl">네 향기를 맡으면</p>
<p class="p-msl">퍼져 퍼져 또 커져 커져</p>
<p class="p-msl highlighted">중독 되어 버렸어</p>
<p class="p-msl">찔려버렸어 hurt</p>
<p class="p-msl">사랑과 아픔 그 단어 사이</p>
<p class="p-msl">You’re so awesome</p>
<p class="p-msl">하지마 남몰래 눈짓하는 거</p>
<p class="p-msl">하지마 날 보며 살짝 웃는 거</p>
<p class="p-msl">내 머린 말해 No</p>
<p class="p-msl">but 가슴이 말해 Oh yes</p>
<p class="p-msl">미칠 것 같으니까 I don’t know</p>
<p class="p-msl">싹 다 All in</p>
<p class="p-msl highlighted">니가 날 만지면 온몸이 반응해</p>
<p class="p-msl highlighted">니가 있어야 살 수 있어</p>
<p class="p-msl">Every day every night</p>
<p class="p-msl">I can feel you</p>
<p class="p-msl">넌 너무 아름다워</p>
<p class="p-msl">눈을 뗄 수가 없어</p>
<p class="p-msl highlighted">꽃에 핀 가시같이 찔릴 것 같아도</p>
<p class="p-msl highlighted">널 갖고 싶어</p>
<p class="p-msl">So beautiful so beautiful</p>
<p class="p-msl">넌 너무 예뻐 슬프도록 아름다워</p>
<p class="p-msl">Too beautiful to handle</p>
<p class="p-msl">나도 알아 절대 가질 수 없단 걸</p>
<p class="p-msl">바라보기만 할 때 더 아름답단 걸</p>
<p class="p-msl">널 지켜줄게 더 예쁘게 피어줘</p>
<p class="p-msl">Ma one & only baby</p>
<p class="p-msl highlighted">다쳐도 좋아 난 괜찮아</p>
<p class="p-msl">Cuz you're ma one & only beautiful</p>
<p class="p-msl">넌 너무 아름다워</p>
<p class="p-msl">눈을 뗄 수가 없어</p>
<p class="p-msl highlighted">꽃에 핀 가시같이 찔릴 것 같아도</p>
<p class="p-msl highlighted">널 갖고 싶어</p>
<p class="p-msl">So beautiful so beautiful</p>
<p class="p-msl">넌 너무 예뻐 슬프도록 아름다워</p>
<p class="p-msl">Too beautiful to handle</p>
`;
