const lyric_im_gonna_crazy = `
<p class="p-msl">OK you got me going crazy</p>
<p class="p-msl">I don't know what to do</p>
<p class="p-msl">I need you</p>
<p class="p-msl">I need you Babe Babe Babe</p>
<p class="p-msl">안녕이란 말은 하지말아</p>
<p class="p-msl">I want you Babe Babe Babe</p>
<p class="p-msl">왜 이리 사랑이 힘든건지</p>
<p class="p-msl highlighted">너 제발 Stop Stop</p>
<p class="p-msl highlighted">Breaking my heart I love you girl</p>
<p class="p-msl">Stop Stop Breaking my heart</p>
<p class="p-msl">I need you girl</p>
<p class="p-msl">Stop Stop Breaking my heart</p>
<p class="p-msl">I love you girl</p>
<p class="p-msl">대체 아리송한 니 속을</p>
<p class="p-msl">난 알 수 없잖아</p>
<p class="p-msl highlighted">뭐하는 거야 왜 이리 연락이 안 돼</p>
<p class="p-msl highlighted">혹시 다른 사람이라도 생긴거야</p>
<p class="p-msl highlighted">보고싶단 말이야 이건 정말 아니야</p>
<p class="p-msl highlighted">내 전화 왜 피해 너 장난치지마</p>
<p class="p-msl">실감조차도 나질않아</p>
<p class="p-msl highlighted">너 하나 곁에 없으니 나</p>
<p class="p-msl highlighted">매일매일 하루하루가</p>
<p class="p-msl highlighted">내겐 그저 지옥같아</p>
<p class="p-msl">죽도록 너무 아픈데</p>
<p class="p-msl">미칠 듯이 힘든데</p>
<p class="p-msl">니가 찢어놓은 내 맘 나 어떡해</p>
<p class="p-msl">I need you Babe Babe Babe</p>
<p class="p-msl">안녕이란 말은 하지말아</p>
<p class="p-msl">I want you Babe Babe Babe</p>
<p class="p-msl">왜 이리 사랑이 힘든건지</p>
<p class="p-msl highlighted">너 제발 Stop Stop</p>
<p class="p-msl highlighted">Breaking my heart I love you girl</p>
<p class="p-msl">Stop Stop Breaking my heart</p>
<p class="p-msl">I need you girl</p>
<p class="p-msl">Stop Stop Breaking my heart</p>
<p class="p-msl">I love you girl</p>
<p class="p-msl">대체 아리송한 니 속을</p>
<p class="p-msl">난 알 수 없잖아</p>
<p class="p-msl highlighted">미친 듯 지우려고 애써봐도</p>
<p class="p-msl highlighted">다 소용없는 내맘</p>
<p class="p-msl highlighted">아무리 봐도 내겐</p>
<p class="p-msl highlighted">오직 너 하나뿐인 내맘</p>
<p class="p-msl">You're the One One</p>
<p class="p-msl">Can't get u outta Ma mind</p>
<p class="p-msl highlighted">부르지도 못할 널</p>
<p class="p-msl highlighted">못 잊어 울고있어 나만</p>
<p class="p-msl">금방 잊혀지겠지 뭐 잠깐</p>
<p class="p-msl">하던 날은 자꾸 늘어가</p>
<p class="p-msl">돌아올꺼란 착각 괴롭히는걸</p>
<p class="p-msl">아무래도 이러다 너땜에 미치겠어</p>
<p class="p-msl highlighted">돌아와 돌아와 여기서 기다릴께</p>
<p class="p-msl">I need you Babe Babe Babe</p>
<p class="p-msl">안녕이란 말은 하지말아</p>
<p class="p-msl">I want you Babe Babe Babe</p>
<p class="p-msl">왜 이리 사랑이 힘든건지</p>
<p class="p-msl highlighted">너 제발 Stop Stop</p>
<p class="p-msl highlighted">Breaking my heart I love you girl</p>
<p class="p-msl">Stop Stop Breaking my heart</p>
<p class="p-msl">I need you girl</p>
<p class="p-msl">Stop Stop Breaking my heart</p>
<p class="p-msl">I love you girl</p>
<p class="p-msl">대체 아리송한 니 속을</p>
<p class="p-msl">난 알 수 없잖아</p>
<p class="p-msl">I love u girl Oh my girl</p>
<p class="p-msl">니 생각에 나 정말 미치겠어</p>
<p class="p-msl">I miss u girl Oh my girl</p>
<p class="p-msl">오늘따라 니가 보고 싶잖아</p>
<p class="p-msl">one two three four Everybody</p>
<p class="p-msl">come on Here we Go</p>
<p class="p-msl">Teen Top Go Go</p>
<p class="p-msl">Put your Hands up High High</p>
<p class="p-msl">one two three four</p>
<p class="p-msl">Everybody come on Here we Go</p>
<p class="p-msl">Teen Top Go Go</p>
<p class="p-msl">Put your Hands up High High</p>
`;
const lyric_i_was_wrong = `
<p class="p-msl">어려도 아픈건 똑같아</p>
<p class="p-msl">세상을 잘 모른다고</p>
<p class="p-msl">아픈걸 모르진 않아</p>
<p class="p-msl">괜찮아 질거라고 왜 거짓말을 해</p>
<p class="p-msl">이렇게 아픈 가슴이 어떻게 쉽게 낫겠어</p>
<p class="p-msl highlighted">너 없이 어떻게 살겠어 그래서 난</p>
<p class="p-msl highlighted">죽어도 못 보내 내가 어떻게 널 보내</p>
<p class="p-msl">가려거든 떠나려거든 내 가슴 고쳐내</p>
<p class="p-msl">아프지 않게 나 살아갈 수라도 있게</p>
<p class="p-msl">안 된다면 어차피 못살 거</p>
<p class="p-msl">죽어도 못 보내</p>
<p class="p-msl">아무리 니가 날 밀쳐도</p>
<p class="p-msl">끝까지 붙잡을 거야</p>
<p class="p-msl">어디도 가지 못하게</p>
<p class="p-msl">정말 갈거라면 거짓말을 해</p>
<p class="p-msl">내일 다시 만나자고 웃으면서 보자고</p>
<p class="p-msl">헤어지잔 말은 농담이라고 아니면 난</p>
<p class="p-msl highlighted">죽어도 못 보내 내가 어떻게 널 보내</p>
<p class="p-msl">가려거든 떠나려거든 내 가슴 고쳐내</p>
<p class="p-msl">아프지 않게 나 살아갈 수라도 있게</p>
<p class="p-msl">안 된다면 어차피 못살 거</p>
<p class="p-msl">죽어도 못 보내</p>
<p class="p-msl">그 많은 시간을 함께 겪었는데</p>
<p class="p-msl highlighted">이제와 어떻게 혼자 살란 거야</p>
<p class="p-msl">그렇겐 못해 난 못해</p>
<p class="p-msl highlighted">죽어도 못 보내 정말로 못 보내</p>
<p class="p-msl">내가 어떻게 널 보내</p>
<p class="p-msl">가려거든 떠나려거든 내 가슴 고쳐내</p>
<p class="p-msl highlighted">아프지 않게 나 살아갈 수라도 있게</p>
<p class="p-msl">안 된다면 어차피 못살 거</p>
<p class="p-msl">죽어도 못 보내</p>
`;
const lyric_why_so_lonely = `
<p class="p-msl">너와 입술이 닿을 때부터 </p>
<p class="p-msl">모든 게 달라질 줄 알았는데</p>
<p class="p-msl">별거 없어 넌 다른 게 없어</p>
<p class="p-msl">너와 보내는 주말 밤이</p>
<p class="p-msl">아주 달콤할 거라 믿었는데</p>
<p class="p-msl">별거 없어 넌 다를 게 없어</p>
<p class="p-msl">어이없어 영화에 나오는 예쁜 연인들처럼</p>
<p class="p-msl">나나난난 그런 사랑을 원하는데</p>
<p class="p-msl highlighted">Baby why I'm so lonely</p>
<p class="p-msl highlighted">난 애타는데 넌 뭐니</p>
<p class="p-msl">Baby no 내 마음이</p>
<p class="p-msl">언제 널 떠나 버릴지 몰라</p>
<p class="p-msl">Tell me why</p>
<p class="p-msl">뭐야 니 맘은 도대체</p>
<p class="p-msl highlighted">뭐야 내가 얼마나 널</p>
<p class="p-msl highlighted">사랑하는 데 이렇게 답답한 기분은 뭔데</p>
<p class="p-msl">뭔가 콩깍지가 씌었는데</p>
<p class="p-msl">너도 나만큼 빠져야 하는데</p>
<p class="p-msl">너만 멋져 내 마음만 다쳐</p>
<p class="p-msl">괜찮을 거라고 Mind control</p>
<p class="p-msl">해도 예상 밖에 있는 내 남잔</p>
<p class="p-msl">Out of control 잔소리만 넘쳐</p>
<p class="p-msl">어이없어 알면 알수록 모르겠어</p>
<p class="p-msl">맘이 왜 자꾸 외로워지는지</p>
<p class="p-msl">나나난난 텅 빈 방안에 </p>
<p class="p-msl">혼자 갇혀버린 것 같아 </p>
<p class="p-msl highlighted">Baby why I'm so lonely</p>
<p class="p-msl highlighted">난 애타는데 넌 뭐니</p>
<p class="p-msl">Baby no 내 마음이</p>
<p class="p-msl">언제 널 떠나 버릴지 몰라</p>
<p class="p-msl">Tell me why</p>
<p class="p-msl">뭐야 니 맘은 도대체</p>
<p class="p-msl">뭐야 내가 얼마나 널사랑하는 데 </p>
<p class="p-msl">이렇게 답답한 기분은 뭔데</p>
<p class="p-msl">I don’t wanna talk about it</p>
<p class="p-msl">말하지 않아도 모두 다 알아 봐주길</p>
<p class="p-msl">아 이건 내 그저 가벼운 바램일 뿐</p>
<p class="p-msl">귓가엔 그저 스치는 바람일 뿐</p>
<p class="p-msl">귀찮다는 듯 얼굴을 구겨 뭐든 대충대충 </p>
<p class="p-msl">당연하단 듯 너는 우겨 담엔 더 잘해줄게 응</p>
<p class="p-msl">다음이 어디 있어 </p>
<p class="p-msl">네 이번 기회 떠나기 전</p>
<p class="p-msl">오 아직도 넌 정신 못 차리면 </p>
<p class="p-msl">뻥 차기 직전</p>
<p class="p-msl highlighted">Baby why I'm so lonely</p>
<p class="p-msl highlighted">난 애타는데 넌 뭐니</p>
<p class="p-msl">Baby no 내 마음이</p>
<p class="p-msl">언제 널 떠나버릴지 몰라</p>
<p class="p-msl">Tell me why</p>
<p class="p-msl">뭐야 니 맘은 도대체</p>
<p class="p-msl">뭐야 내가 얼마나 널</p>
<p class="p-msl">사랑하는 데 이렇게 답답한 기분은 뭔데</p>
<p class="p-msl">뭐야 니 맘은 도대체</p>
<p class="p-msl">뭐야 내가 얼마나 널</p>
<p class="p-msl">사랑하는 데 이렇게 답답한 기분은 뭔데</p>
<p class="p-msl">뭐야</p>
`;

const lyric_never_goodbye = `
<p class="p-msl">변해가는 계절들을 막아 줄 거란</p>
<p class="p-msl">그런 말로 너를 붙잡을 순 없지만</p>
<p class="p-msl">많은 계절을 마주칠 너에게</p>
<p class="p-msl">이 마음 하날 비춰주려 해</p>
<p class="p-msl"></p>
<p class="p-msl">떠나는 걸음이 맘이 흐려지지 않게</p>
<p class="p-msl">So please don't cry 약속할 테니</p>
<p class="p-msl"></p>
<p class="p-msl">유난히 짙고 긴 밤 견디던 어느 날</p>
<p class="p-msl">눈물을 참지 못해 문득 고개를 들면</p>
<p class="p-msl">반짝이는 별을 따라</p>
<p class="p-msl">다시 돌아올 길을 찾을 거야</p>
<p class="p-msl">It's Never Goodbye</p>
<p class="p-msl"></p>
<p class="p-msl">네가 지금 가야 하는 길이</p>
<p class="p-msl">나와 엇갈릴 수도 있어</p>
<p class="p-msl">항상 같은 방향을 걸을 수 없단 걸</p>
<p class="p-msl">I know I know I know (I know)</p>
<p class="p-msl highlighted">함께 가는 방법을 찾을 수 없다면</p>
<p class="p-msl highlighted">너를 멀리서 늘 비춰줄 거야</p>
<p class="p-msl"></p>
<p class="p-msl">난 그대로야 여전해 Like a photo</p>
<p class="p-msl">시간은 근데 그렇지 않더라고</p>
<p class="p-msl">이거 듣고 기억들을 간지럽혀</p>
<p class="p-msl">I see you 눈을 감아도</p>
<p class="p-msl">You know that’s not normal for you</p>
<p class="p-msl">I’m not normal</p>
<p class="p-msl"></p>
<p class="p-msl highlighted">잠시 놓쳐도 단번에 찾을 수 있게</p>
<p class="p-msl highlighted">그 자리에서 기다릴게</p>
<p class="p-msl highlighted">우린 It’s Never Goodbye</p>
<p class="p-msl highlighted">다시 돌고 돌아 어둠 속에서</p>
<p class="p-msl" highlighted>내가 너를 알아보듯 언젠가</p>
<p class="p-msl highlighted">Find me please</p>
<p class="p-msl"></p>
<p class="p-msl">멈춰 선 내 맘이 다시 달려가지 않게</p>
<p class="p-msl">So please don't cry 약속할 테니</p>
<p class="p-msl"></p>
<p class="p-msl">유난히 짙고 긴 밤 견디던 어느 날</p>
<p class="p-msl">눈물을 참지 못해 문득 고개를 들면</p>
<p class="p-msl">반짝이는 별을 따라</p>
<p class="p-msl">다시 돌아올 길을 찾을 거야</p>
<p class="p-msl">It's Never Goodbye</p>
<p class="p-msl"></p>
<p class="p-msl highlighted">언젠가 나에게 돌아오는 날</p>
<p class="p-msl highlighted">한 걸음에 널 마중 갈게</p>
<p class="p-msl highlighted">You were you are you and I</p>
<p class="p-msl highlighted">항상 함께 일 거야</p>
<p class="p-msl highlighted">그때는 엇갈리지 마</p>
<p class="p-msl"></p>
<p class="p-msl">유난히 짙고 긴 밤 견디던 어느 날</p>
<p class="p-msl">눈물을 참지 못해 문득 고개를 들면</p>
<p class="p-msl">반짝이는 별을 따라</p>
<p class="p-msl">다시 돌아올 길을 찾을 거야</p>
<p class="p-msl">It's Never Goodbye</p>
<p class="p-msl"></p>
<p class="p-msl">You never say goodbye</p>
<p class="p-msl">같은 시간 같은자리 같은 공간 속</p>
<p class="p-msl">밝혀줘 어둠 속 Starlight</p>
<p class="p-msl">너로 인해 나의 하나뿐인 별자리가</p>
<p class="p-msl">완성되어가길 바라</p>
<p class="p-msl"></p>
<p class="p-msl highlighted">불안해하지 마 난 너를 보고 있어</p>
<p class="p-msl highlighted">같이 있던 밤 기억하고 있어</p>
<p class="p-msl">낯선 길을 걸을 땐 고개를 들어</p>
<p class="p-msl">저 별을 바라봐</p>
`;

const lyric_hello_futrue = `
<p class="p-msl">Big dreams and big thrills</p>
<p class="p-msl">Flying high 터무니없는 상상해봐</p>
<p class="p-msl">네 눈앞에 달려들고 있는 별</p>
<p class="p-msl">낚아 채 불을 태워 봐</p>
<p class="p-msl"></p>
<p class="p-msl">시작이라는 걸 넌 믿을 수 있겠니?</p>
<p class="p-msl highlighted">이제야 사랑을 알 것 같아</p>
<p class="p-msl highlighted">Ready or not 가는 거야 나를 믿어</p>
<p class="p-msl">Soldiers knocking doors down yelling out</p>
<p class="p-msl"></p>
<p class="p-msl">전쟁 전쟁 같던 시간들은</p>
<p class="p-msl">모두 뒤로 보내 가슴이 소리치네</p>
<p class="p-msl">달려가 날아 봐</p>
<p class="p-msl">If you're rocking with me oh oh</p>
<p class="p-msl"></p>
<p class="p-msl">Here we go here we go satellite radio</p>
<p class="p-msl">내 미래에 전해 줘</p>
<p class="p-msl">온 세상과 저 광야 위로</p>
<p class="p-msl">후회 없이 사랑했다고 말하게</p>
<p class="p-msl"></p>
<p class="p-msl highlighted">기다렸어 어서 와</p>
<p class="p-msl highlighted">어디든 we’re coming together</p>
<p class="p-msl highlighted">아무 걱정 하지 마</p>
<p class="p-msl highlighted">잘 될 거야 Hello Future</p>
<p class="p-msl highlighted">너를 만나 같이 더 빛나 yeah yeah</p>
<p class="p-msl">Ey we’re on the way up we’re on the way up</p>
<p class="p-msl">아름다운 시간만 쌓자 yeah yeah yeah</p>
<p class="p-msl">We’re going way up we’re going</p>
<p class="p-msl"></p>
<p class="p-msl">On our way up Hello Future</p>
<p class="p-msl">On our way up Hello Future</p>
<p class="p-msl"></p>
<p class="p-msl">Ey 미래의 너를 조우하게 됐어</p>
<p class="p-msl">경계 위로 손을 맞대면</p>
<p class="p-msl">우린 너무 닮아 있어</p>
<p class="p-msl">뭘 더 찾게 될지 결국 웃게 될지</p>
<p class="p-msl">지금부턴 운명이라고 해</p>
<p class="p-msl"></p>
<p class="p-msl">Fire fire 자욱한 연기 속에</p>
<p class="p-msl">살아남은 키 작은 꽃처럼</p>
<p class="p-msl">같은 시간 속에 너를 사랑하고 있어</p>
<p class="p-msl"></p>
<p class="p-msl">Here we go here we go</p>
<p class="p-msl">날개를 펼치고</p>
<p class="p-msl highlighted">또 꺾이고 다쳐도</p>
<p class="p-msl highlighted">누구보다 강한 너잖아</p>
<p class="p-msl highlighted">미래의 미래에도 널 사랑할 나란 걸</p>
<p class="p-msl"></p>
<p class="p-msl highlighted">기다렸어 어서 와</p>
<p class="p-msl highlighted">어디든 we’re coming together</p>
<p class="p-msl highlighted">아무 걱정 하지 마</p>
<p class="p-msl highlighted">잘 될 거야 Hello Future</p>
<p class="p-msl highlighted">너를 만나 같이 더 빛나 yeah yeah</p>
<p class="p-msl">Ey we’re on the way up we’re on the way up</p>
<p class="p-msl">아름다운 시간만 쌓자 yeah yeah</p>
<p class="p-msl">We’re going way up we’re going</p>
<p class="p-msl"></p>
<p class="p-msl">Ey I’m tryna’ center me</p>
<p class="p-msl">hey where your center be?</p>
<p class="p-msl">흔들리지 않게 걸어 나아갈 수 있을지</p>
<p class="p-msl">Too many cynical 거꾸로 갔던 Entropy</p>
<p class="p-msl">그 어디쯤 너 기다리고 있을지</p>
<p class="p-msl"></p>
<p class="p-msl">멀지 않아 눈을 떠 봐</p>
<p class="p-msl">내가 원한 모든 건 너뿐이라고</p>
<p class="p-msl">we’re on our way up</p>
<p class="p-msl"></p>
<p class="p-msl">타 버린 채 여린 온기의</p>
<p class="p-msl">남은 잿더미 속에 ready to clap back</p>
<p class="p-msl">그리 멀지 않은 peace</p>
<p class="p-msl">아픈 시간이 다만 짧기를 바라고 또 원했지</p>
<p class="p-msl">Who you gon’ believe?</p>
<p class="p-msl"></p>
<p class="p-msl highlighted">기다렸어 어서 와</p>
<p class="p-msl highlighted">어디든 we’re coming together</p>
<p class="p-msl highlighted">아무 걱정 하지 마</p>
<p class="p-msl highlighted">잘 될 거야 Hello Future</p>
<p class="p-msl highlighted">너를 만나 같이 더 빛나 yeah yeah</p>
<p class="p-msl">Ey we’re on the way up we’re on the way up</p>
<p class="p-msl">아름다운 시간만 쌓자 yeah</p>
<p class="p-msl">We’re going way up we’re going</p>
<p class="p-msl"></p>
<p class="p-msl">We’re going way up</p>
<p class="p-msl">곁에 함께 있어줘</p>
<p class="p-msl highlighted">오직 너만이 내 미래라는 걸</p>
<p class="p-msl highlighted">Just keep looking to the stars</p>
<p class="p-msl highlighted">널 기다렸어</p>
<p class="p-msl highlighted">Hello Future</p>
`;
const lyric_its_me = `
<p class="p-msl highlighted">너를 보던 그 순간</p>
<p class="p-msl highlighted">Pick me Pick me Pick me</p>
<p class="p-msl highlighted">시선 고정 너에게</p>
<p class="p-msl">Pick me Pick me Pick me</p>
<p class="p-msl">눈부셔 Shining Shining</p>
<p class="p-msl">제발 내 맘을 Pick me Pick me</p>
<p class="p-msl">Pick me Pick me Pick me</p>
<p class="p-msl highlighted">너와 있는 이 시간</p>
<p class="p-msl highlighted">Pick me Pick me Pick me</p>
<p class="p-msl highlighted">난 너무 빨라 불안해</p>
<p class="p-msl">Pick me Pick me Pick me</p>
<p class="p-msl">멈춰줘 hold me hold me</p>
<p class="p-msl">마지막까지 Pick me Pick me</p>
<p class="p-msl highlighted">너는 내게 너무 예뻐서</p>
<p class="p-msl highlighted">꿈일까 난 너무 두려워</p>
<p class="p-msl">기억해 제발 이 순간 Tonight</p>
<p class="p-msl">오늘 밤 주인공은 나야 나 나야 나</p>
<p class="p-msl">너만을 기다려 온 나야 나 나야 나</p>
<p class="p-msl">네 맘을 훔칠 사람 나야 나 나야 나</p>
<p class="p-msl">마지막 단 한 사람 나야 나 나야 나</p>
<p class="p-msl">오늘 밤 주인공은 나야 나 나야 나</p>
<p class="p-msl">너만을 기다려 온 나야 나 나야 나</p>
<p class="p-msl">네 맘을 훔칠 사람 나야 나 나야 나</p>
<p class="p-msl">마지막 단 한 사람 나야 나 나야 나</p>
<p class="p-msl">Pick me Pick me up</p>
<p class="p-msl">Pick me Pick me Pick me</p>
<p class="p-msl">Pick me Pick me up</p>
<p class="p-msl">Pick me Pick me Pick me</p>
<p class="p-msl">Pick me Pick me up</p>
<p class="p-msl">Pick me Pick me Pick me</p>
<p class="p-msl">Pick me Pick me up</p>
<p class="p-msl">내가 아닌듯한 나</p>
<p class="p-msl">Pick me Pick me Pick me</p>
<p class="p-msl">미쳤어 내게 빠졌어</p>
<p class="p-msl">Pick me Pick me Pick me</p>
<p class="p-msl">I'm so Sick Crazy Crazy</p>
<p class="p-msl">제발 내 맘을 Pick me Pick me</p>
<p class="p-msl">Pick me Pick me Pick me</p>
<p class="p-msl">너를 보면 볼수록</p>
<p class="p-msl">Pick me Pick me Pick me</p>
<p class="p-msl">난 막지 못해 내 마음</p>
<p class="p-msl">Pick me Pick me Pick me</p>
<p class="p-msl">이제는 Call me Call me</p>
<p class="p-msl">말해줘 내게 빠져 버렸다고</p>
<p class="p-msl">너무나 예뻐서 꿈일까 두려워</p>
<p class="p-msl">Oh 빛나는 환상 속의 그대</p>
<p class="p-msl">날 바라봐줘 너의 맘속으로</p>
<p class="p-msl">들어가 함께하고 싶어</p>
<p class="p-msl">오늘 밤 주인공은 나야 나 나야 나</p>
<p class="p-msl">너만을 기다려 온 나야 나 나야 나</p>
<p class="p-msl">네 맘을 훔칠 사람 나야 나 나야 나</p>
<p class="p-msl">마지막 단 한 사람 나야 나 나야 나</p>
<p class="p-msl">오늘 밤 주인공은 나야 나 나야 나</p>
<p class="p-msl">너만을 기다려 온 나야 나 나야 나</p>
<p class="p-msl">네 맘을 훔칠 사람 나야 나 나야 나</p>
<p class="p-msl">마지막 단 한 사람 나야 나 나야 나</p>
<p class="p-msl">Pick me Pick me up</p>
<p class="p-msl">Pick me Pick me Pick me</p>
<p class="p-msl">Pick me Pick me up</p>
<p class="p-msl">Pick me Pick me Pick me</p>
<p class="p-msl">Pick me Pick me up</p>
<p class="p-msl">Pick me Pick me Pick me</p>
<p class="p-msl">Pick me Pick me up</p>
`;

const lyric_my_universe = `
<p class="p-msl highlighted">You, you are my universe and</p>
<p class="p-msl highlighted">I just want to put you first</p>
<p class="p-msl highlighted">And you, you are my universe, and I…</p>
<p class="p-msl"></p>
<p class="p-msl">In the night I lie and look up at you</p>
<p class="p-msl">When the morning comes I watch you rise</p>
<p class="p-msl">There’s a paradise they couldn’t capture</p>
<p class="p-msl">That bright infinity inside your eyes</p>
<p class="p-msl"></p>
<p class="p-msl">매일 밤 네게 날아가 (가)</p>
<p class="p-msl">꿈이란 것도 잊은 채</p>
<p class="p-msl">나 웃으며 너를 만나 (나)</p>
<p class="p-msl">Never ending forever baby</p>
<p class="p-msl"></p>
<p class="p-msl highlighted">You, you are my universe and</p>
<p class="p-msl highlighted">I just want to put you first</p>
<p class="p-msl highlighted">And you, you are my universe, and</p>
<p class="p-msl highlighted">You make my world light up inside</p>
<p class="p-msl"></p>
<p class="p-msl">어둠이 내겐 더 편했었지</p>
<p class="p-msl">길어진 그림자 속에서 (eyes)</p>
<p class="p-msl"></p>
<p class="p-msl">And they said that we can’t be together</p>
<p class="p-msl">Because</p>
<p class="p-msl">Because we come from different sides</p>
<p class="p-msl"></p>
<p class="p-msl highlighted">You, you are my universe and</p>
<p class="p-msl highlighted">I just want to put you first</p>
<p class="p-msl highlighted">And you, you are my universe, and</p>
<p class="p-msl highlighted">You make my world light up inside</p>
<p class="p-msl"></p>
<p class="p-msl">My universe (do do, do do)</p>
<p class="p-msl">My universe (do do, do do)</p>
<p class="p-msl">My universe (do do, do do)</p>
<p class="p-msl">(you make my world)</p>
<p class="p-msl">You make my world light up inside</p>
<p class="p-msl"></p>
<p class="p-msl">Make my world light up inside</p>
<p class="p-msl"></p>
<p class="p-msl highlighted">나를 밝혀주는 건</p>
<p class="p-msl highlighted">너란 사랑으로 수 놓아진 별</p>
<p class="p-msl highlighted">내 우주의 넌</p>
<p class="p-msl highlighted">또 다른 세상을 만들어 주는 걸</p>
<p class="p-msl"></p>
<p class="p-msl highlighted">너는 내 별이자 나의 우주니까</p>
<p class="p-msl">지금 이 시련도 결국엔 잠시니까</p>
<p class="p-msl">너는 언제까지나 지금처럼 밝게만 빛나줘</p>
<p class="p-msl">우리는 너를 따라 이 긴 밤을 수놓을 거야</p>
<p class="p-msl"></p>
<p class="p-msl">너와 함께 날아가 (가)</p>
<p class="p-msl">When I’m without you I’m crazy</p>
<p class="p-msl">자 어서 내 손을 잡아 (아)</p>
<p class="p-msl">We are made of each other baby</p>
<p class="p-msl"></p>
<p class="p-msl highlighted">You, you are my universe and</p>
<p class="p-msl highlighted">I just want to put you first</p>
<p class="p-msl highlighted">And you, you are my universe, and</p>
<p class="p-msl highlighted">You make my world light up inside</p>
<p class="p-msl"></p>
<p class="p-msl">My universe (you, you are)</p>
<p class="p-msl">My universe (I just want)</p>
<p class="p-msl">My universe (you, you are)</p>
<p class="p-msl">My universe, and I</p>
<p class="p-msl"></p>
<p class="p-msl">My universe</p>
`;
const lyric_super_hot = `
<p class="p-msl">get up get up then get down get down</p>
<p class="p-msl">get up get up and party</p>
<p class="p-msl">get up get up then get down get down</p>
<p class="p-msl highlighted">저기 걸어오는 그녀 눈이 부시네</p>
<p class="p-msl">Imma going crazy you know it</p>
<p class="p-msl highlighted">도도히 고갤 돌려 아 내 맘 설레네</p>
<p class="p-msl highlighted">어질어질하네 다른 별에서 왔나</p>
<p class="p-msl">Fashionista 나도 한 멋짐 하는데</p>
<p class="p-msl">Funky sister 오늘 힘 좀 줘봤어 나</p>
<p class="p-msl">딴 늑대들 쳐다 보지마</p>
<p class="p-msl">내 그녀가 닳는단 말야</p>
<p class="p-msl">Let me take you out now</p>
<p class="p-msl">우리 지금 가자</p>
<p class="p-msl">오늘 나와 데이트하는 거야</p>
<p class="p-msl">우 실감이 안나</p>
<p class="p-msl">우 네가 내 여자니</p>
<p class="p-msl highlighted">앞모습도 뒷모습도 완전 여신이야</p>
<p class="p-msl">Uh uh I gotta tell you what</p>
<p class="p-msl">미치겠어 to have a girl like this is</p>
<p class="p-msl">Super Hot She's Super Hot</p>
<p class="p-msl">나나나나나나나 예</p>
<p class="p-msl highlighted">넌 태양보다 뜨거워 메가톤 Bomb</p>
<p class="p-msl highlighted">She's Hot Too Super Hot</p>
<p class="p-msl highlighted">나나나나나나나 예</p>
<p class="p-msl highlighted">Get up get up 넌 특별한 Girl</p>
<p class="p-msl">Girl she's Super Hot</p>
<p class="p-msl">get up get up then get down get down</p>
<p class="p-msl">get up get up and party</p>
<p class="p-msl">get up get up then get down get down</p>
<p class="p-msl">오늘 밤에 너와 Party</p>
<p class="p-msl">넌 그냥 완벽 남에겐 철벽</p>
<p class="p-msl">내게 주는 눈빛조차 아까워</p>
<p class="p-msl">come on 넌 나의 girl 여기에 sit down</p>
<p class="p-msl">돌아가는 back back 유턴은 노 없지</p>
<p class="p-msl">오늘이 날이야 너와나 party야</p>
<p class="p-msl">I'm gonna get up get up 너와 춤추지</p>
<p class="p-msl highlighted">아 나 정신 없어 왜 이렇게 예뻐 너</p>
<p class="p-msl">Fashionista 너와 잘 어울리지 나</p>
<p class="p-msl">Funky sister 오늘 차려 입었어 나</p>
<p class="p-msl">딴 늑대들 쳐다 보지마</p>
<p class="p-msl">내 그녀가 닳는단 말야</p>
<p class="p-msl">Let me take you out now</p>
<p class="p-msl">우리 지금 가자</p>
<p class="p-msl">오늘 나와 데이트하는 거야</p>
<p class="p-msl highlighted">우 실감이 안나</p>
<p class="p-msl highlighted">우 네가 내 여자니</p>
<p class="p-msl highlighted">앞모습도 뒷모습도 완전 여신이야</p>
<p class="p-msl">Uh uh I gotta tell you what</p>
<p class="p-msl">미치겠어 to have a girl like this is</p>
<p class="p-msl">Super Hot She's Super Hot</p>
<p class="p-msl highlighted">나나나나나나나 예</p>
<p class="p-msl highlighted">넌 태양보다 뜨거워 메가톤 Bomb</p>
<p class="p-msl highlighted">She's Hot Too Super Hot</p>
<p class="p-msl highlighted">나나나나나나나 예</p>
<p class="p-msl highlighted">Get up get up 넌 특별한 Girl</p>
<p class="p-msl highlighted">Girl she's Super Hot</p>
<p class="p-msl">get up get up then get down get down</p>
<p class="p-msl">get up get up and party</p>
<p class="p-msl">get up get up then get down get down</p>
<p class="p-msl">오늘 밤에 너는 Super Hot</p>
<p class="p-msl">get up get up then get down get down</p>
<p class="p-msl">get up get up and party</p>
<p class="p-msl">get up get up then get down get down</p>
<p class="p-msl">오늘 밤에 너와 Party</p>
<p class="p-msl">Listen up girl 나나나나나나나 예</p>
<p class="p-msl">우리 더 이상 말은 필요 없지</p>
<p class="p-msl">Fashionista you're making me</p>
<p class="p-msl">feel so good now</p>
<p class="p-msl">Funky sister 이 구역의 여신은 너</p>
<p class="p-msl">딴 늑대들 쳐다 보지마</p>
<p class="p-msl">내 그녀가 닳는단 말야</p>
<p class="p-msl">Let me take you out now</p>
<p class="p-msl">우리 지금 가자</p>
<p class="p-msl">오늘 나와 데이트하는 거야</p>
<p class="p-msl">Let me take you out now</p>
<p class="p-msl">우리 지금 가자</p>
<p class="p-msl">오늘 나와 파티하는 거야 날밤 새</p>
<p class="p-msl">Super Hot She's Super Hot</p>
<p class="p-msl highlighted">나나나나나나나 예</p>
<p class="p-msl highlighted">넌 태양보다 뜨거워 메가톤 Bomb</p>
<p class="p-msl highlighted">She's Hot Too Super Hot</p>
<p class="p-msl highlighted">나나나나나나나 예</p>
<p class="p-msl highlighted">Get up get up 넌 특별한 Girl</p>
<p class="p-msl highlighted">Girl she's Super Hot</p>
<p class="p-msl">get up get up then get down get down</p>
<p class="p-msl">get up get up and party</p>
<p class="p-msl">get up get up then get down get down</p>
<p class="p-msl">오늘 밤에 너와 Party</p>
<p class="p-msl">She's Hot Too Super Hot</p>
<p class="p-msl">나나나나나나나 예</p>
<p class="p-msl highlighted">get up get up 넌 특별한 Girl</p>
<p class="p-msl">Girl she's Super Hot</p>
<p class="p-msl">get up get up then get down get down</p>
<p class="p-msl">get up get up and party</p>
<p class="p-msl">get up get up then get down get down</p>
<p class="p-msl">오늘 밤에 너와 Party</p>

`;

const lyric_10_out_of_10 = `
<p class="p-msl">That girl 너무 예뻐</p>
<p class="p-msl">Oh my god 기가 막혀</p>
<p class="p-msl highlighted">이건 본 적이 없는 그런 아름다움이야</p>
<p class="p-msl highlighted">말로 설명해도 알아듣지 못할거야</p>
<p class="p-msl highlighted">책 속에서나 볼 수 있는</p>
<p class="p-msl highlighted">꿈 속에서나 만나보는</p>
<p class="p-msl highlighted">그런 여자란 말야</p>
<p class="p-msl">날이면 날마다 오지 않아</p>
<p class="p-msl">뒷모습이 너무 사람을 괴롭게 해</p>
<p class="p-msl">착한 나를 자꾸 나쁜 맘을 먹게 해</p>
<p class="p-msl">이건 참을 수가 없어 정말 너무나 괴로워</p>
<p class="p-msl">영화 미녀는 괴로월 볼 때 보다 더 괴로워</p>
<p class="p-msl highlighted">그녀의 입술은 맛있어 입술은 맛있어</p>
<p class="p-msl highlighted">10점 만점에 10점</p>
<p class="p-msl highlighted">그녀의 다리는 멋져 다리는 멋져</p>
<p class="p-msl highlighted">10점 만점에 10점</p>
<p class="p-msl highlighted">그녀의 날리는 머릿결 날리는 머릿결</p>
<p class="p-msl highlighted">10점 만점에 10점</p>
<p class="p-msl highlighted">그녀는 머리에서 발끝까지 모두 다</p>
<p class="p-msl highlighted">10점 만점에 10점</p>
<p class="p-msl highlighted">나를 보고 웃는데 10점</p>
<p class="p-msl highlighted">말하는 목소리가 10점</p>
<p class="p-msl highlighted">만나면 만나 볼 수록 어쩜</p>
<p class="p-msl highlighted">빈틈이 없어 Yes sir Yes sir</p>
<p class="p-msl">그녀 때문에 정말 미쳤어</p>
<p class="p-msl">하루라도 안 볼 수가 없어</p>
<p class="p-msl">어제 너무 바빠 하루 쉬었어</p>
<p class="p-msl">그러자 입에 가시가 돋쳤어 Oh</p>
<p class="p-msl">뒷모습이 너무 사람을 괴롭게 해</p>
<p class="p-msl">착한 나를 자꾸 나쁜 맘을 먹게 해</p>
<p class="p-msl">눈이 떨어지질 않아 정말 말이 되질 않아</p>
<p class="p-msl">이건 야한 만화영화 보다 더 야한 것 같아</p>
<p class="p-msl highlighted">그녀의 입술은 맛있어 입술은 맛있어</p>
<p class="p-msl highlighted">10점 만점에 10점</p>
<p class="p-msl highlighted">그녀의 다리는 멋져 다리는 멋져</p>
<p class="p-msl highlighted">10점 만점에 10점</p>
<p class="p-msl highlighted">그녀의 날리는 머릿결 날리는 머릿결</p>
<p class="p-msl highlighted">10점 만점에 10점</p>
<p class="p-msl highlighted">그녀는 머리에서 발끝까지 모두 다</p>
<p class="p-msl highlighted">10점 만점에 10점</p>
<p class="p-msl">라라 랄랄라 랄라 Pretty baby</p>
<p class="p-msl">라라 랄랄라 랄라 Be my lady</p>
<p class="p-msl">라라 랄랄라 랄라 Pretty baby</p>
<p class="p-msl">라라 랄랄라 랄라 Be my lady</p>
<p class="p-msl">라라 랄랄라 난 빠졌잖아</p>
<p class="p-msl highlighted">그녀 없이 사는 건 해보나마나</p>
<p class="p-msl highlighted">그녀가 주는게 너무나 많아</p>
<p class="p-msl highlighted">내 입에서 미소가 끊이질 않아</p>
<p class="p-msl highlighted">그녀 없인 사나 마나</p>
<p class="p-msl highlighted">그럼 이제 나는 어떻게 하나</p>
<p class="p-msl">에라 모르겠다 이대로가 좋다</p>
<p class="p-msl">그녀가 술이면 취해 버리련다</p>
<p class="p-msl highlighted">그녀의 입술은 맛있어 입술은 맛있어</p>
<p class="p-msl highlighted">10점 만점에 10점</p>
<p class="p-msl highlighted">그녀의 다리는 멋져 다리는 멋져</p>
<p class="p-msl highlighted">10점 만점에 10점</p>
<p class="p-msl highlighted">그녀의 날리는 머릿결 날리는 머릿결</p>
<p class="p-msl highlighted">10점 만점에 10점</p>
<p class="p-msl highlighted">그녀는 머리에서 발끝까지 모두 다</p>
<p class="p-msl highlighted">10점 만점에 10점</p>
<p class="p-msl">Haha 10점 만점에 10점</p>
<p class="p-msl">You know what it is 10점 만점에 10점</p>
<p class="p-msl">It's JYP 10점 만점에 10점</p>
<p class="p-msl">And 2PM baby 10점 만점에 10점</p>

`;

const lyric_trouble_maker = `
<p class="p-msl">1 2 3</p>
<p class="p-msl">니 눈을 보면 난</p>
<p class="p-msl">Trouble Maker</p>
<p class="p-msl">니 곁에 서면 난</p>
<p class="p-msl">Trouble Maker</p>
<p class="p-msl">조금씩 더 더 더</p>
<p class="p-msl">갈수록 더 더 더</p>
<p class="p-msl">이젠 내 맘을</p>
<p class="p-msl">나도 어쩔 수 없어</p>
<p class="p-msl highlighted">니가 나를 잊지 못하게</p>
<p class="p-msl highlighted">자꾸 니 앞에서 또</p>
<p class="p-msl highlighted">니 맘 자꾸 내가 흔들어</p>
<p class="p-msl highlighted">벗어날 수 없도록</p>
<p class="p-msl">니 입술을 또 훔치고</p>
<p class="p-msl">멀리 달아나버려</p>
<p class="p-msl">난 Trou a a a ble Trouble</p>
<p class="p-msl">Trou Trouble Maker</p>
<p class="p-msl">Trouble Maker Trouble Maker</p>
<p class="p-msl">Trouble Maker Trouble Maker</p>
<p class="p-msl highlighted">니 맘을 깨물고 도망칠 거야</p>
<p class="p-msl highlighted">고양이처럼 넌 자꾸 안달이 날 거야</p>
<p class="p-msl highlighted">내 앞으로 와 어서 화내보렴</p>
<p class="p-msl highlighted">내 섹시한 걸음 니 머리 속에</p>
<p class="p-msl highlighted">발동을 거는 은근한 스킨십</p>
<p class="p-msl highlighted">얼굴에 비친 못 참아 죽겠단 니 눈빛</p>
<p class="p-msl">갈수록 깊이 더 빠져들어 알수록</p>
<p class="p-msl">니가 더 맘에 들어 Baby</p>
<p class="p-msl">아무래도 니 생각에 취했나봐</p>
<p class="p-msl">Lady I never never never stop</p>
<p class="p-msl highlighted">니가 나를 잊지 못하게</p>
<p class="p-msl highlighted">자꾸 니 앞에서 또</p>
<p class="p-msl highlighted">니 맘 자꾸 내가 흔들어</p>
<p class="p-msl highlighted">벗어날 수 없도록</p>
<p class="p-msl">니 입술을 또 훔치고</p>
<p class="p-msl">멀리 달아나버려</p>
<p class="p-msl">난 Trou a a a ble Trouble</p>
<p class="p-msl">Trou Trouble Maker</p>
<p class="p-msl">Trouble Maker Trouble Maker</p>
<p class="p-msl">Trouble Maker Trouble Maker</p>
<p class="p-msl">어떻게 널 내 맘에</p>
<p class="p-msl">담아둘 수 있는지 Trouble Maker</p>
<p class="p-msl">그냥 내 맘이 가는대로</p>
<p class="p-msl">이젠 I never never stop</p>
<p class="p-msl">멈출 수 없어</p>
<p class="p-msl highlighted">니가 나를 잊지 못하게</p>
<p class="p-msl highlighted">자꾸 니 앞에서 또</p>
<p class="p-msl highlighted">니 맘 자꾸 내가 흔들어</p>
<p class="p-msl highlighted">벗어날 수 없도록</p>
<p class="p-msl">니 입술을 또 훔치고</p>
<p class="p-msl">멀리 달아나버려</p>
<p class="p-msl">난 Trou a a a ble Trouble</p>
<p class="p-msl">Trou Trouble Maker</p>
<p class="p-msl">Trouble Maker Trouble Maker</p>
<p class="p-msl">Trouble Maker Trouble Maker</p>
`;

const lyric_illusion = `
<p class="p-msl">You’re so yummy yummy yummy</p>
<p class="p-msl">In my tummy tummy tummy</p>
<p class="p-msl"></p>
<p class="p-msl">Look at you 빨라지는 걸음걸이</p>
<p class="p-msl">Look at me 호기심을 자극하지</p>
<p class="p-msl">Look at them 알아챌 수 없는 거리</p>
<p class="p-msl">Baby don’t panic 한밤의 Party</p>
<p class="p-msl"></p>
<p class="p-msl">차올라 달이 딱 좋은 Timing</p>
<p class="p-msl">이건 비밀이야 쉿 우리만의</p>
<p class="p-msl highlighted">한밤의 Party 널 끌어당김</p>
<p class="p-msl highlighted">어쩌니 내게 뺏겨버린 환심</p>
<p class="p-msl"></p>
<p class="p-msl">몽롱한 기분이 좋은 Tonight</p>
<p class="p-msl">색다른 세계로 이끄는 Light</p>
<p class="p-msl"></p>
<p class="p-msl">Follow me, Come and get illusion</p>
<p class="p-msl">한입에 삼켜 널 Delicious</p>
<p class="p-msl">아찔한 미끼로 Hook up</p>
<p class="p-msl">관심을 먹고 Growing up</p>
<p class="p-msl">Follow me, Come and get illusion</p>
<p class="p-msl">몸집을 불려가 Delicious</p>
<p class="p-msl">점점 더 커지는 Fire</p>
<p class="p-msl">관심을 먹고 Growing up</p>
<p class="p-msl"></p>
<p class="p-msl highlighted">(Will o' the wisp)</p>
<p class="p-msl highlighted">겁내지 말고 이리 온</p>
<p class="p-msl highlighted">(Will o' the wisp)</p>
<p class="p-msl highlighted">겁내지 말고 이리 온</p>
<p class="p-msl"></p>
<p class="p-msl">Easy peasy 너도 알다시피</p>
<p class="p-msl">When you dizzy 내겐 그저 Dish</p>
<p class="p-msl">도깨비불 너를 놀려 Boo</p>
<p class="p-msl">예상 못 한 순간 등장하지 불쑥</p>
<p class="p-msl"></p>
<p class="p-msl">첨 보는 Style 멋모를 Timing</p>
<p class="p-msl">너의 약점에다 Hit! It’s so funny</p>
<p class="p-msl">한밤의 Party 널 끌어당김</p>
<p class="p-msl">알아도 막을 수 없는 반칙</p>
<p class="p-msl"></p>
<p class="p-msl">낯선 이 기분이 묘한 Tonight</p>
<p class="p-msl highlighted">감춰둔 본능을 이끄는 Light</p>
<p class="p-msl"></p>
<p class="p-msl">Follow me, Come and get illusion</p>
<p class="p-msl">한입에 삼켜 널 Delicious</p>
<p class="p-msl">아찔한 미끼로 Hook up</p>
<p class="p-msl">관심을 먹고 Growing up</p>
<p class="p-msl">Follow me, Come and get illusion</p>
<p class="p-msl">몸집을 불려가 Delicious</p>
<p class="p-msl">점점 더 커지는 Fire</p>
<p class="p-msl">관심을 먹고 Growing up</p>
<p class="p-msl highlighted">(Will o' the wisp)</p>
<p class="p-msl highlighted">겁내지 말고 이리 온</p>
<p class="p-msl highlighted">(Will o' the wisp)</p>
<p class="p-msl highlighted">겁내지 말고 이리 온</p>
<p class="p-msl"></p>
<p class="p-msl">Yummy yummy yummy</p>
<p class="p-msl">In your tummy tummy tummy</p>
<p class="p-msl">놀란 너의 Face 나를 저격하는 Taste</p>
<p class="p-msl">멀리멀리 달아나도 소용없어 이미</p>
<p class="p-msl">Come get illusion</p>
<p class="p-msl">So fool</p>
<p class="p-msl"></p>
<p class="p-msl">Follow me, Come and get illusion</p>
<p class="p-msl">유일한 목격자 You’re the one</p>
<p class="p-msl">방심한 틈을 타 Swallow</p>
<p class="p-msl">환상을 먹고 Growing up</p>
<p class="p-msl">Follow me, Come and get illusion</p>
<p class="p-msl">순진한 먹잇감 Delicious</p>
<p class="p-msl">단번에 노리는 Hunter</p>
<p class="p-msl">네 맘을 뺏어 Growing up</p>
<p class="p-msl"></p>
<p class="p-msl highlighted">(Will o' the wisp)</p>
<p class="p-msl highlighted">겁내지 말고 이리 온</p>
<p class="p-msl highlighted">(Will o' the wisp)</p>
<p class="p-msl highlighted">겁내지 말고 이리 온</p>
`;

const lyric_lipstic = `
<p class="p-msl">립스틱 스틱 세우고</p>
<p class="p-msl">립스틱 스틱 세우고</p>
<p class="p-msl">어찌나 눈이 높던지</p>
<p class="p-msl">애인이 있는 건지</p>
<p class="p-msl">살짝 시크해보여</p>
<p class="p-msl">하나도 관심 없는 척</p>
<p class="p-msl">속이는 거 다 알아</p>
<p class="p-msl">흘리고 다니잖아</p>
<p class="p-msl">오똑한 콧날에 베일 것 같아</p>
<p class="p-msl">짜릿 짜릿 네 눈빛에 녹을 것 같아</p>
<p class="p-msl">구릿빛 피부가 달콤해 보여</p>
<p class="p-msl highlighted">아슬아슬 다가가서 훔치고 싶어</p>
<p class="p-msl highlighted">립스틱 스틱 세우고</p>
<p class="p-msl highlighted">내 입술에 바르고</p>
<p class="p-msl highlighted">잘 다려진 하얀 셔츠 위에</p>
<p class="p-msl highlighted">살짝 묻히고</p>
<p class="p-msl" highlighted>립스틱 스틱 세우고</p>
<p class="p-msl" highlighted>네 입술에 맞추고</p>
<p class="p-msl highlighted">아찔아찔 솟은 쇄골 위에</p>
<p class="p-msl highlighted">몰래 묻히고 어머어머</p>
<p class="p-msl highlighted">어어어어 어머어머</p>
<p class="p-msl">몰래 묻히고 어머어머</p>
<p class="p-msl">어어어어 어머어머</p>
<p class="p-msl">어쩌다 그리 된 건지</p>
<p class="p-msl">사연이 있는 건지</p>
<p class="p-msl">살짝 화가나 보여</p>
<p class="p-msl">사실 좀 미안하지만</p>
<p class="p-msl">즐기는 거 다 알아</p>
<p class="p-msl">몰래 웃고 있잖아</p>
<p class="p-msl">촉촉한 눈빛에 빠질 것 같아</p>
<p class="p-msl">찌릿 찌릿 네 향기에 취할 것 같아</p>
<p class="p-msl">우윳빛 피부가 눈부셔 보여</p>
<p class="p-msl">아슬아슬 다가가서 훔치고 싶어</p>
<p class="p-msl highlighted">립스틱 스틱 세우고</p>
<p class="p-msl highlighted">내 입술에 바르고</p>
<p class="p-msl highlighted">잘 다려진 하얀 셔츠 위에</p>
<p class="p-msl highlighted">살짝 묻히고</p>
<p class="p-msl highlighted">립스틱 스틱 세우고</p>
<p class="p-msl highlighted">네 입술에 맞추고</p>
<p class="p-msl highlighted">아찔아찔 솟은 쇄골 위에</p>
<p class="p-msl highlighted">몰래 묻히고 어머어머</p>
<p class="p-msl highlighted">어어어어 어머어머</p>
<p class="p-msl highlighted">몰래 묻히고 어머어머</p>
<p class="p-msl highlighted">어어어어 어머어머</p>
<p class="p-msl">좀 빼지마 가만히 둘 순 없어</p>
<p class="p-msl">널 널 널</p>
<p class="p-msl">이러지마 오늘 처음 봤잖아</p>
<p class="p-msl">립스틱 스틱 세우고</p>
<p class="p-msl">내 입술에 바르고</p>
<p class="p-msl">잘 다려진 하얀 셔츠 위에</p>
<p class="p-msl">살짝 묻히고</p>
<p class="p-msl">립스틱 스틱 세우고</p>
<p class="p-msl">네 입술에 맞추고</p>
<p class="p-msl">아찔아찔 솟은 쇄골 위에</p>
<p class="p-msl">몰래 묻히고 어머어머</p>
<p class="p-msl">어어어어 어머어머</p>
<p class="p-msl">몰래 묻히고 어머어머</p>
<p class="p-msl">어어어어 어머어머</p>

`;

const lyric_i_feel_you = `
<p class="p-msl">내게 걸어놓은 마법이 뭔지</p>
<p class="p-msl">헤어 나오질 못하고 있어</p>
<p class="p-msl">한번도 이런 적이 없이</p>
<p class="p-msl">흔들린 적이 없었던 난데 No</p>
<p class="p-msl highlighted">Woo 하루 종일 이래 네 생각에 취해</p>
<p class="p-msl highlighted">Woo 기다리기만 해 널 만나러 가게</p>
<p class="p-msl">Woo woo baby 어쩌면 좋아</p>
<p class="p-msl highlighted">너 없인 못 살 것만 같아</p>
<p class="p-msl">Woo baby</p>
<p class="p-msl">I Feel You</p>
<p class="p-msl">혼자 있어도 너의 손길이 느껴져</p>
<p class="p-msl">하루 종일 나를 만져</p>
<p class="p-msl">I Feel You</p>
<p class="p-msl highlighted">빠져있는데 헤어나올 수가 없어</p>
<p class="p-msl highlighted">너에게 달려갈 생각뿐이 없어</p>
<p class="p-msl highlighted">점점 더 빠져만 가</p>
<p class="p-msl highlighted">점점 더 미쳐만 가</p>
<p class="p-msl">점점 더 어떻게 나 Baby</p>
<p class="p-msl">네 손길이 아직도 나를스치고 있는 것만 같아</p>
<p class="p-msl">네 목소리가 내 귓가에</p>
<p class="p-msl">계속 속삭이는 것만 같아 No</p>
<p class="p-msl highlighted">Woo 하루 종일 이래 네 생각에 취해</p>
<p class="p-msl highlighted">Woo 기다리기만 해 널 만나러 가게</p>
<p class="p-msl">Woo woo baby 어쩌면 좋아</p>
<p class="p-msl highlighted">너 없인 못 살 것만 같아</p>
<p class="p-msl">Woo babyI Feel You</p>
<p class="p-msl">혼자 있어도 너의 손길이 느껴져</p>
<p class="p-msl">하루 종일 나를 만져</p>
<p class="p-msl">I Feel You</p>
<p class="p-msl highlighted">빠져있는데 헤어나올 수가 없어</p>
<p class="p-msl highlighted">너에게 달려갈 생각뿐이 없어</p>
<p class="p-msl">눈 감아도 들려달콤한 숨결 느껴</p>
<p class="p-msl">그만 날 보고 불 꺼니 시선이 더 날 붉혀</p>
<p class="p-msl">손발 끝 간질거려와</p>
<p class="p-msl">달아오르는 체온 숨 가빠와</p>
<p class="p-msl">더 이상은 참을 수가 없어 나</p>
<p class="p-msl">이제 Please baby be mine</p>
<p class="p-msl">I Feel You</p>
<p class="p-msl">혼자 있어도 너의 손길이 느껴져</p>
<p class="p-msl">하루 종일 나를 만져</p>
<p class="p-msl">I Feel You</p>
<p class="p-msl highlighted">빠져있는데 헤어나올 수가 없어</p>
<p class="p-msl highlighted">너에게 달려갈 생각뿐이 없어</p>
<p class="p-msl">점점 더 빠져만 가</p>
<p class="p-msl">점점 더 미쳐만 가</p>
<p class="p-msl">점점 더 어떻게 나</p>
<p class="p-msl">Baby</p>

`;

const lyric_heart_attack = `
<p class="p-msl">A ye Brave sound</p>
<p class="p-msl">And it goes a little something like this</p>
<p class="p-msl">완전 반해 반해 버렸어요</p>
<p class="p-msl">부드러운 목소리에</p>
<p class="p-msl highlighted">반해 반해 버렸어요</p>
<p class="p-msl highlighted">난 떨려</p>
<p class="p-msl">AOA Let's Go</p>
<p class="p-msl highlighted">내가 미쳤나 봐 왜 또 이러지</p>
<p class="p-msl highlighted">내 마음 열여덟 소녀 마냥</p>
<p class="p-msl highlighted">막 쿵쿵대</p>
<p class="p-msl highlighted">숨길 수 없나 봐 난 매일 이러지</p>
<p class="p-msl highlighted">눈이라도 마주치면</p>
<p class="p-msl highlighted">귀까지 확 빨개져</p>
<p class="p-msl">이해 못해</p>
<p class="p-msl">네가 걔를 못 봐서 그래</p>
<p class="p-msl">딱 첫눈에 확 반해 버린다는 말에</p>
<p class="p-msl">그 마음 이해 가더라</p>
<p class="p-msl">나도 좀 알겠더라</p>
<p class="p-msl highlighted">널 처음 본 그 순간</p>
<p class="p-msl highlighted">완전 반해 반해 버렸어요</p>
<p class="p-msl">넓은 어깨 날렵한 눈매에</p>
<p class="p-msl">부드러운 목소리에</p>
<p class="p-msl">반해 반해 버렸어요</p>
<p class="p-msl highlighted">너의 얇고 긴 손가락만 봐도</p>
<p class="p-msl highlighted">난 떨려</p>
<p class="p-msl highlighted">어머나 자꾸만 심쿵해</p>
<p class="p-msl highlighted">널 보면 볼수록</p>
<p class="p-msl highlighted">가슴이 쿵쿵대 나도 모르겠어</p>
<p class="p-msl highlighted">심쿵해 나 어쩌면 좋아</p>
<p class="p-msl">자꾸만 네 품에</p>
<p class="p-msl">꼭 안기고 싶어 baby</p>
<p class="p-msl highlighted">어쩌다 눈이라도 마주치면</p>
<p class="p-msl highlighted">난 심쿵 거려</p>
<p class="p-msl highlighted">너의 작은 관심이라도 받을까</p>
<p class="p-msl highlighted">아등바등 거려</p>
<p class="p-msl">너는 대체 걔가 뭐가 그리 좋아</p>
<p class="p-msl">라고 묻는 친구들에게 말해</p>
<p class="p-msl">야 모르면 말을 말어</p>
<p class="p-msl">이해 못해 네가 걔를 못 봐서 그래</p>
<p class="p-msl">딱 첫눈에 확 반해 버린다는 말에</p>
<p class="p-msl">그 마음 이해 가더라</p>
<p class="p-msl">나도 좀 알겠더라</p>
<p class="p-msl highlighted">널 처음 본 그 순간</p>
<p class="p-msl highlighted">완전 반해 반해 버렸어요</p>
<p class="p-msl">넓은 어깨 날렵한 눈매에</p>
<p class="p-msl">부드러운 목소리에</p>
<p class="p-msl">반해 반해 버렸어요</p>
<p class="p-msl highlighted">너의 얇고 긴 손가락만 봐도</p>
<p class="p-msl highlighted">난 떨려</p>
<p class="p-msl highlighted">어머나 자꾸만 심쿵해</p>
<p class="p-msl highlighted">널 보면 볼수록</p>
<p class="p-msl highlighted">가슴이 쿵쿵대 나도 모르겠어</p>
<p class="p-msl highlighted">심쿵해 나 어쩌면 좋아</p>
<p class="p-msl">자꾸만 네 품에</p>
<p class="p-msl">꼭 안기고 싶어 baby</p>
<p class="p-msl">오 나의 왕자님 어디를 보나요</p>
<p class="p-msl">바로 여기 내가 있는데요</p>
<p class="p-msl">너무나 멋진 그대</p>
<p class="p-msl">난 그대 하나면 돼</p>
<p class="p-msl">난 그대 없이 못 살아요</p>
<p class="p-msl">완전 반해 반해 버렸어요</p>
<p class="p-msl">부드러운 목소리에</p>
<p class="p-msl highlighted">반해 반해 버렸어요</p>
<p class="p-msl highlighted">난 떨려</p>
<p class="p-msl highlighted">어머나 자꾸만 심쿵해</p>
<p class="p-msl">Everybody say What AOA</p>
<p class="p-msl">쿵쿵대</p>
<p class="p-msl">And it goes a little something like this</p>
<p class="p-msl">심쿵해</p>
<p class="p-msl">한번 더 say What AOA</p>
<p class="p-msl">네 품에 꼭 안기고 싶어 baby</p>
`;

const lyric_gee = `
<p class="p-msl">Uh Huh Listen Boy </p>
<p class="p-msl">My First Love Story </p>
<p class="p-msl">My Angel and My Girl</p>
<p class="p-msl">My Sunshine</p>
<p class="p-msl">Uh Uh Let's go</p>
<p class="p-msl">너무 너무 멋져 눈이 눈이 부셔</p>
<p class="p-msl highlighted">숨을 못 쉬겠어 떨리는 Girl</p>
<p class="p-msl">Gee Gee Gee Gee Baby Baby Baby</p>
<p class="p-msl">Gee Gee Gee Gee Baby Baby Baby</p>
<p class="p-msl highlighted">너무 부끄러워 쳐다 볼 수 없어</p>
<p class="p-msl highlighted">사랑에 빠져서 수줍은 Girl</p>
<p class="p-msl">Gee Gee Gee Gee Baby Baby Baby</p>
<p class="p-msl">Gee Gee Gee Gee</p>
<p class="p-msl">Be Be Be Be Be Be</p>
<p class="p-msl">어떻게 하죠</p>
<p class="p-msl">어떡 어떡하죠</p>
<p class="p-msl">떨리는 나는</p>
<p class="p-msl" highlighted>떨리는 나는요</p>
<p class="p-msl highlighted">두근 두근 두근 두근두근 두근거려</p>
<p class="p-msl highlighted">밤엔 잠도 못 이루죠</p>
<p class="p-msl">나는 나는 바본가봐요</p>
<p class="p-msl highlighted">그대 그대밖에 모르는 바보</p>
<p class="p-msl">그래요 그댈 보는 난</p>
<p class="p-msl">너무 반짝 반짝 눈이 부셔</p>
<p class="p-msl">No No No No No</p>
<p class="p-msl">너무 깜짝 깜짝 놀란 나는</p>
<p class="p-msl">Oh Oh Oh Oh Oh</p>
<p class="p-msl">너무 짜릿 짜릿 몸이 떨려</p>
<p class="p-msl">Gee Gee Gee Gee Gee</p>
<p class="p-msl">Oh 젖은 눈빛 Oh Yeah</p>
<p class="p-msl">좋은 향기 Oh Yeah Yeah Yeah</p>
<p class="p-msl">너무 너무 예뻐 맘이 너무 예뻐</p>
<p class="p-msl">첫 눈에 반했어 꼭 짚은 Girl</p>
<p class="p-msl">Gee Gee Gee Gee Baby Baby Baby</p>
<p class="p-msl">Gee Gee Gee Gee Baby Baby Baby</p>
<p class="p-msl highlighted">너무나 뜨거워 만질 수가 없어</p>
<p class="p-msl highlighted">사랑에 타버려 후끈한 Girl</p>
<p class="p-msl">Gee Gee Gee Gee Baby Baby Baby</p>
<p class="p-msl">Gee Gee Gee GeeBe Be Be Be Be Be</p>
<p class="p-msl">어쩌면 좋아</p>
<p class="p-msl">어쩌면 좋아요</p>
<p class="p-msl">수줍은 나는</p>
<p class="p-msl highlighted">수줍은 나는요</p>
<p class="p-msl highlighted">몰라 몰라 몰라 몰라몰라 몰라 하며</p>
<p class="p-msl highlighted">매일 그대만 그리죠</p>
<p class="p-msl">친한 친구들은 말하죠</p>
<p class="p-msl">정말 너는 정말 못 말려</p>
<p class="p-msl">바보 하지만 그댈 보는 난</p>
<p class="p-msl">너무 반짝 반짝 눈이 부셔</p>
<p class="p-msl">No No No No No</p>
<p class="p-msl">너무 깜짝 깜짝 놀란 나는</p>
<p class="p-msl">Oh Oh Oh Oh Oh</p>
<p class="p-msl">너무 짜릿 짜릿 몸이 떨려</p>
<p class="p-msl">Gee Gee Gee Gee Gee</p>
<p class="p-msl">Oh 젖은 눈빛 Oh Yeah</p>
<p class="p-msl">좋은 향기 Oh Yeah Yeah Yeah</p>
<p class="p-msl">말도 못했는 걸</p>
<p class="p-msl">너무 부끄러워 하는 난</p>
<p class="p-msl">용기가 없는 걸까</p>
<p class="p-msl">어떡해야 좋은걸까</p>
<p class="p-msl highlighted">두근 두근 맘 졸이며</p>
<p class="p-msl highlighted">바라보고 있는 난</p>
<p class="p-msl">너무 반짝 반짝 눈이 부셔</p>
<p class="p-msl">No No No No No</p>
<p class="p-msl">너무 깜짝 깜짝 놀란 나는</p>
<p class="p-msl">Oh Oh Oh Oh Oh</p>
<p class="p-msl">너무 짜릿 짜릿 몸이 떨려</p>
<p class="p-msl">Gee Gee Gee Gee Gee</p>
<p class="p-msl">Oh 젖은 눈빛 Oh Yeah</p>
<p class="p-msl">좋은 향기 Oh Yeah</p>
<p class="p-msl">너무 반짝 반짝 눈이 부셔</p>
<p class="p-msl">No No No No No</p>
<p class="p-msl">너무 깜짝 깜짝 놀란 나는</p>
<p class="p-msl">Oh Oh Oh Oh Oh</p>
<p class="p-msl">너무 짜릿 짜릿 몸이 떨려</p>
<p class="p-msl">Gee Gee Gee Gee Gee</p>
<p class="p-msl">Oh 젖은 눈빛 Oh Yeah</p>
<p class="p-msl">좋은 향기 Oh Yeah Yeah Yeah</p>
`;
const lyric_boodoo_doll = `
<p class="p-msl">나를 불러 네가 맘이 아플 때</p>
<p class="p-msl">내게만 털어놔 누굴 원하는데</p>
<p class="p-msl">시간을 돌려줄까</p>
<p class="p-msl">마음을 갖다 줄까</p>
<p class="p-msl">잊을 수 없을 땐 가져야 하잖아</p>
<p class="p-msl">나를 믿고 따라 해봐</p>
<p class="p-msl">그는 내게 돌아온다</p>
<p class="p-msl">시간은 너의 편</p>
<p class="p-msl">넌 그냥 기다려라</p>
<p class="p-msl">그가 널 울린 만큼</p>
<p class="p-msl">내가 다 울려줄게</p>
<p class="p-msl ">째깍 째깍 다 이뤄지리라</p>
<p class="p-msl">가질 수 없다면</p>
<p class="p-msl highlighted">그냥 널 위해 살겠어</p>
<p class="p-msl highlighted">얼마든지 너라면</p>
<p class="p-msl highlighted">다칠 준비가 돼 있어</p>
<p class="p-msl">이제부터 잘 봐 내가 뭘 하는지</p>
<p class="p-msl highlighted">너라면 한 몸 아깝지 않은 나</p>
<p class="p-msl">이름만 대 누구든</p>
<p class="p-msl">내가 다 데려올 거야</p>
<p class="p-msl">째깍 째깍 다 이뤄지리라</p>
<p class="p-msl highlighted">안길 수 없다면 날 밟고 일어서</p>
<p class="p-msl">누구도 함부로 널 못 대하게</p>
<p class="p-msl">어떠한 이유라 해도</p>
<p class="p-msl">넌 내가 필요하다</p>
<p class="p-msl">널 위해 싸우는</p>
<p class="p-msl">인형이 돼 줄 나</p>
<p class="p-msl">아픈 눈을 질끈 감고</p>
<p class="p-msl">너를 위해 달려간다</p>
<p class="p-msl">제발 나를 떠나지만 마라</p>
<p class="p-msl" highlighted>네가 원하는 건 다 가져다줄게</p>
<p class="p-msl">째깍 째깍 다 이뤄지리라</p>
<p class="p-msl">망가진다 해도</p>
<p class="p-msl">너의 손끝에서라면</p>
<p class="p-msl">온 세상의 눈물을</p>
<p class="p-msl">다 흘릴 내가 여기 있어</p>
<p class="p-msl">이제부터 잘 봐 내가 뭘 하는지</p>
<p class="p-msl highlighted">너라면 한 몸 아깝지 않은 나</p>
<p class="p-msl">이름만 대 누구든</p>
<p class="p-msl">내가 다 데려올 거야</p>
<p class="p-msl">째깍 째깍 다 이뤄지리라</p>
<p class="p-msl">Should I go Should I stay</p>
<p class="p-msl">Nobody knows Whoo</p>
<p class="p-msl">Should I go Should I stay</p>
<p class="p-msl">Nobody knows Whoo</p>
<p class="p-msl">Yeah 지옥의 문을 열어라</p>
<p class="p-msl">그녀를 눈물 흘리게 만든</p>
<p class="p-msl">죄인아 피눈물 흘려라</p>
<p class="p-msl">불러라 저주의 노래 네</p>
<p class="p-msl">내면에 감춘 분노들을 말해 봐</p>
<p class="p-msl highlighted">내 육신은 널 위한 제물이돼</p>
<p class="p-msl highlighted">네 행복에 나를 바칠게</p>
<p class="p-msl">웃는 너의 얼굴 한 번이면 족해</p>
<p class="p-msl">내가 대신 다 해 네가 바라는 것</p>
<p class="p-msl">내 남은 시간들이 줄어든대도</p>
<p class="p-msl">누가 됐든 잘 봐 그녈 울리지 마</p>
<p class="p-msl">더 이상 잃을 무엇도 없는 나</p>
<p class="p-msl">그 누구도 모르는</p>
<p class="p-msl">내 가슴속의 슬픔은</p>
<p class="p-msl">째깍 째깍 다 사라지리라</p>
<p class="p-msl">Should I go Should I stay</p>
<p class="p-msl">Nobody knows Whoo</p>
<p class="p-msl">Should I go Should I stay</p>
<p class="p-msl">Nobody knows Whoo</p>
<p class="p-msl">다 이뤄지리라</p>
`;

const lyric_fake_love = `
<p class="p-msl highlighted">널 위해서라면 난</p>
<p class="p-msl highlighted">슬퍼도 기쁜 척 할 수가 있었어</p>
<p class="p-msl highlighted">널 위해서라면 난</p>
<p class="p-msl highlighted">아파도 강한 척 할 수가 있었어</p>
<p class="p-msl">사랑이 사랑만으로 완벽하길</p>
<p class="p-msl">내 모든 약점들은 다 숨겨지길</p>
<p class="p-msl">이뤄지지 않는 꿈속에서</p>
<p class="p-msl">피울 수 없는 꽃을 키웠어</p>
<p class="p-msl">I'm so sick of this</p>
<p class="p-msl">Fake Love Fake Love Fake Love</p>
<p class="p-msl">I'm so sorry but it's</p>
<p class="p-msl">Fake Love Fake Love Fake Love</p>
<p class="p-msl">I wanna be a good man just for you</p>
<p class="p-msl">세상을 줬네 just for you</p>
<p class="p-msl">전부 바꿨어 just for you</p>
<p class="p-msl">Now I dunno me who are you</p>
<p class="p-msl">우리만의 숲 너는 없었어</p>
<p class="p-msl">내가 왔던 route 잊어버렸어</p>
<p class="p-msl">나도 내가 누구였는지도</p>
<p class="p-msl">잘 모르게 됐어</p>
<p class="p-msl">거울에다 지껄여봐 너는 대체 누구니</p>
<p class="p-msl highlighted">널 위해서라면 난</p>
<p class="p-msl highlighted">슬퍼도 기쁜 척 할 수가 있었어</p>
<p class="p-msl highlighted">널 위해서라면 난</p>
<p class="p-msl highlighted">아파도 강한 척 할 수가 있었어</p>
<p class="p-msl">사랑이 사랑만으로 완벽하길</p>
<p class="p-msl">내 모든 약점들은 다 숨겨지길</p>
<p class="p-msl">이뤄지지 않는 꿈속에서</p>
<p class="p-msl">피울 수 없는 꽃을 키웠어</p>
<p class="p-msl">Love you so bad Love you so bad</p>
<p class="p-msl highlighted">널 위해 예쁜 거짓을 빚어내</p>
<p class="p-msl">Love it’s so mad</p>
<p class="p-msl">Love it’s so mad</p>
<p class="p-msl highlighted">날 지워 너의 인형이 되려 해</p>
<p class="p-msl">Love you so bad</p>
<p class="p-msl">Love you so bad</p>
<p class="p-msl highlighted">널 위해 예쁜 거짓을 빚어내</p>
<p class="p-msl">Love it’s so mad</p>
<p class="p-msl">Love it’s so mad</p>
<p class="p-msl highlighted">날 지워 너의 인형이 되려 해</p>
<p class="p-msl">I'm so sick of this</p>
<p class="p-msl">Fake Love Fake Love Fake Love</p>
<p class="p-msl">I'm so sorry but it's</p>
<p class="p-msl">Fake Love Fake Love Fake Love</p>
<p class="p-msl">Why you sad I don't know 난 몰라</p>
<p class="p-msl">웃어봐 사랑해 말해봐</p>
<p class="p-msl">나를 봐 나조차도 버린 나</p>
<p class="p-msl">너조차 이해할 수 없는 나</p>
<p class="p-msl">낯설다 하네</p>
<p class="p-msl highlighted">니가 좋아하던 나로 변한 내가</p>
<p class="p-msl">아니라 하네</p>
<p class="p-msl">예전에 니가 잘 알고 있던 내가</p>
<p class="p-msl highlighted">아니긴 뭐가 아냐 난 눈 멀었어</p>
<p class="p-msl">사랑은 뭐가 사랑</p>
<p class="p-msl">It's all fake love</p>
<p class="p-msl">Woo I dunno I dunno I dunno why</p>
<p class="p-msl">Woo 나도 날 나도 날 모르겠어</p>
<p class="p-msl">Woo I just know I just know</p>
<p class="p-msl">I just know why</p>
<p class="p-msl">Cuz it’s all Fake Love</p>
<p class="p-msl">Fake Love Fake Love</p>
<p class="p-msl">Love you so bad Love you so bad</p>
<p class="p-msl highlighted">널 위해 예쁜 거짓을 빚어내</p>
<p class="p-msl">Love it’s so mad</p>
<p class="p-msl">Love it’s so mad</p>
<p class="p-msl highlighted">날 지워 너의 인형이 되려 해</p>
<p class="p-msl">Love you so bad Love you so bad</p>
<p class="p-msl highlighted">널 위해 예쁜 거짓을 빚어내</p>
<p class="p-msl">Love it’s so mad</p>
<p class="p-msl">Love it’s so mad</p>
<p class="p-msl highlighted">날 지워 너의 인형이 되려 해</p>
<p class="p-msl">I'm so sick of this</p>
<p class="p-msl">Fake Love Fake Love Fake Love</p>
<p class="p-msl">I'm so sorry but it's</p>
<p class="p-msl">Fake Love Fake Love Fake Love</p>
<p class="p-msl highlighted">널 위해서라면 난</p>
<p class="p-msl highlighted">슬퍼도 기쁜 척 할 수가 있었어</p>
<p class="p-msl highlighted">널 위해서라면 난</p>
<p class="p-msl highlighted">아파도 강한 척 할 수가 있었어</p>
<p class="p-msl">사랑이 사랑만으로 완벽하길</p>
<p class="p-msl">내 모든 약점들은 다 숨겨지길</p>
<p class="p-msl">이뤄지지 않는 꿈속에서</p>
<p class="p-msl">피울 수 없는 꽃을 키웠어</p>
`;

const lyric_beautiful = `<p class="p-msl">왜 너야 미쳐버릴 것 같아</p>
<p class="p-msl">대체 뭐야 반해버린 것 같아</p>
<p class="p-msl">하루 종일 머릿속에 맴맴 돌아버려</p>
<p class="p-msl">물음표가 매일매일</p>
<p class="p-msl">가시 돋친 걸 알면서도 갖고 싶어</p>
<p class="p-msl">red rose</p>
<p class="p-msl">가시 줄기엔 아름다운</p>
<p class="p-msl">장미가 피는 법</p>
<p class="p-msl">진한 빨강 꽃말은 널 사랑한단 것</p>
<p class="p-msl">온 몸에 피가 나도 널 안고 싶어</p>
<p class="p-msl">Cuz I think about you errday</p>
<p class="p-msl">이미 중독인 걸 말해 뭐해</p>
<p class="p-msl">니가 날 만지면 온몸이 반응해</p>
<p class="p-msl">니가 있어야 살 수 있어</p>
<p class="p-msl">Every day every night</p>
<p class="p-msl">I can feel you</p>
<p class="p-msl">넌 너무 아름다워</p>
<p class="p-msl">눈을 뗄 수가 없어</p>
<p class="p-msl highlighted">꽃에 핀 가시같이 찔릴 것 같아도</p>
<p class="p-msl highlighted">널 갖고 싶어</p>
<p class="p-msl">So beautiful so beautiful</p>
<p class="p-msl">넌 너무 예뻐 슬프도록 아름다워</p>
<p class="p-msl">Too beautiful to handle</p>
<p class="p-msl">Two fingers thumbs up</p>
<p class="p-msl">감탄사를 던져 맨 정신을 벗겨</p>
<p class="p-msl">미쳐 돌아버릴 것 같아</p>
<p class="p-msl">네 향기를 맡으면</p>
<p class="p-msl">퍼져 퍼져 또 커져 커져</p>
<p class="p-msl highlighted">중독 되어 버렸어</p>
<p class="p-msl">찔려버렸어 hurt</p>
<p class="p-msl">사랑과 아픔 그 단어 사이</p>
<p class="p-msl">You’re so awesome</p>
<p class="p-msl">하지마 남몰래 눈짓하는 거</p>
<p class="p-msl">하지마 날 보며 살짝 웃는 거</p>
<p class="p-msl">내 머린 말해 No</p>
<p class="p-msl">but 가슴이 말해 Oh yes</p>
<p class="p-msl">미칠 것 같으니까 I don’t know</p>
<p class="p-msl">싹 다 All in</p>
<p class="p-msl highlighted">니가 날 만지면 온몸이 반응해</p>
<p class="p-msl highlighted">니가 있어야 살 수 있어</p>
<p class="p-msl">Every day every night</p>
<p class="p-msl">I can feel you</p>
<p class="p-msl">넌 너무 아름다워</p>
<p class="p-msl">눈을 뗄 수가 없어</p>
<p class="p-msl highlighted">꽃에 핀 가시같이 찔릴 것 같아도</p>
<p class="p-msl highlighted">널 갖고 싶어</p>
<p class="p-msl">So beautiful so beautiful</p>
<p class="p-msl">넌 너무 예뻐 슬프도록 아름다워</p>
<p class="p-msl">Too beautiful to handle</p>
<p class="p-msl">나도 알아 절대 가질 수 없단 걸</p>
<p class="p-msl">바라보기만 할 때 더 아름답단 걸</p>
<p class="p-msl">널 지켜줄게 더 예쁘게 피어줘</p>
<p class="p-msl">Ma one & only baby</p>
<p class="p-msl highlighted">다쳐도 좋아 난 괜찮아</p>
<p class="p-msl">Cuz you're ma one & only beautiful</p>
<p class="p-msl">넌 너무 아름다워</p>
<p class="p-msl">눈을 뗄 수가 없어</p>
<p class="p-msl highlighted">꽃에 핀 가시같이 찔릴 것 같아도</p>
<p class="p-msl highlighted">널 갖고 싶어</p>
<p class="p-msl">So beautiful so beautiful</p>
<p class="p-msl">넌 너무 예뻐 슬프도록 아름다워</p>
<p class="p-msl">Too beautiful to handle</p>
`;
